// AUTO-GENERATED oleh scripts/make-puzzles.js. JANGAN diedit manual.
//
// Setiap entri berasal dari permainan self-play nyata dan diverifikasi ulang oleh
// chess.js: FEN valid, giliran cocok, solusi legal, dan langkahnya benar Advantage
// (skakmat, promosi, atau tangkap yang menguntungkan). Tidak ada teka-teki yang
// tidak bisa dibuktikan papan.
//
// Jalankan ulang:  node scripts/make-puzzles.js   (butuh devDependency chess.js)

export type PuzzleCategory = "opening" | "defense" | "middlegame" | "endgame" | "opponent";
export type PuzzleDifficulty = "Mudah" | "Sedang" | "Sulit";
export type PuzzleMotif = "mate" | "promotion" | "capture" | "capture-check";
/** "quest" = dipakai juga sebagai bab Belajar & Quest, "puzzle" = hanya Bank Teka-Teki. */
export type PuzzleTrack = "quest" | "puzzle";

export type Puzzle = {
  id: string;
  category: PuzzleCategory;
  difficulty: PuzzleDifficulty;
  track: PuzzleTrack;
  fen: string;
  turn: "w" | "b";
  solutionUci: string;
  solutionSan: string;
  motif: PuzzleMotif;
  theme: string;
  description: string;
  hintPiece: string;
  hintExplanation: string;
  trickExplanation: string;
  xp: number;
};

export const PUZZLES: Puzzle[] = [
    {
      "id": "p01",
      "category": "opening",
      "difficulty": "Sulit",
      "xp": 175,
      "track": "puzzle",
      "fen": "rnb1kb1r/p2p1ppp/4p3/qNpn4/5P2/3P2PN/PPPBP2P/R2QKB1R w KQkq - 3 8",
      "turn": "w",
      "solutionUci": "d2a5",
      "solutionSan": "Bxa5",
      "motif": "capture",
      "theme": "Bxa5 — tangkap (pembukaan)",
      "description": "Putih menjawab dengan Bxa5: gajah Putih mengambil sekertaris bernilai 9 pion di a5 (selisih 6 poin). Posisi ini masuk hitungan taktik.",
      "hintPiece": "Gajah Putih",
    },
    {
      "id": "p02",
      "category": "opening",
      "difficulty": "Sulit",
      "xp": 175,
      "track": "puzzle",
      "fen": "r1b1kb1r/p2p1ppp/2n1p3/qNpn4/P4P2/3P2PN/1PPBP2P/R2QKB1R w KQkq - 1 9",
      "turn": "w",
      "solutionUci": "d2a5",
      "solutionSan": "Bxa5",
      "motif": "capture",
      "theme": "Bxa5 — tangkap (pembukaan)",
      "description": "Putih menjawab dengan Bxa5: gajah Putih mengambil sekertaris bernilai 9 pion di a5 (selisih 6 poin). Posisi ini masuk hitungan taktik.",
      "hintPiece": "Gajah Putih",
    },
    {
      "id": "p03",
      "category": "opening",
      "difficulty": "Sedang",
      "xp": 100,
      "track": "puzzle",
      "fen": "r1b1kb1r/3p1ppp/4p3/3n4/q1BnP3/6PN/1PPB1K1P/R1Q4R w kq - 0 15",
      "turn": "w",
      "solutionUci": "a1a4",
      "solutionSan": "Rxa4",
      "motif": "capture",
      "theme": "Rxa4 — tangkap (pembukaan)",
      "description": "Putih menjawab dengan Rxa4: menara Putih mengambil sekertaris bernilai 9 pion di a4 (selisih 4 poin). Posisi ini masuk hitungan taktik.",
      "hintPiece": "Menara Putih",
    },
    {
      "id": "p04",
      "category": "middlegame",
      "difficulty": "Sulit",
      "xp": 175,
      "track": "puzzle",
      "fen": "r1b1k2r/5pp1/3pp2Q/2bB4/R3P3/5KPN/1P5P/4B2R b kq - 0 20",
      "turn": "b",
      "solutionUci": "g7h6",
      "solutionSan": "gxh6",
      "motif": "capture",
      "theme": "gxh6 — tangkap (babak tengah)",
      "description": "Hitam menjawab dengan gxh6: pion Hitam mengambil sekertaris bernilai 9 pion di h6 (selisih 8 poin). Posisi ini masuk hitungan taktik.",
      "hintPiece": "Pion di g7",
    },
    {
      "id": "p05",
      "category": "middlegame",
      "difficulty": "Sedang",
      "xp": 100,
      "track": "puzzle",
      "fen": "rn4nN/p2pk1p1/4p2R/2p5/p3P3/2PB2P1/PP1P2P1/RNB1K3 b Q - 0 15",
      "turn": "b",
      "solutionUci": "g7h6",
      "solutionSan": "gxh6",
      "motif": "capture",
      "theme": "gxh6 — tangkap (babak tengah)",
      "description": "Hitam menjawab dengan gxh6: pion Hitam mengambil menara bernilai 5 pion di h6 (selisih 4 poin). Posisi ini masuk hitungan taktik.",
      "hintPiece": "Pion di g7",
    },
    {
      "id": "p06",
      "category": "middlegame",
      "difficulty": "Sedang",
      "xp": 100,
      "track": "puzzle",
      "fen": "rn5N/p2pk1p1/4pn1R/2p1P3/p7/2PB2P1/PP1P2P1/RNB1K3 b Q - 0 16",
      "turn": "b",
      "solutionUci": "g7h6",
      "solutionSan": "gxh6",
      "motif": "capture",
      "theme": "gxh6 — tangkap (babak tengah)",
      "description": "Hitam menjawab dengan gxh6: pion Hitam mengambil menara bernilai 5 pion di h6 (selisih 4 poin). Posisi ini masuk hitungan taktik.",
      "hintPiece": "Pion di g7",
    },
    {
      "id": "p07",
      "category": "middlegame",
      "difficulty": "Sedang",
      "xp": 100,
      "track": "puzzle",
      "fen": "rn5N/3pk1p1/4pn1R/p1p1P3/p7/2PB2P1/PP1PK1P1/RNB5 b - - 1 17",
      "turn": "b",
      "solutionUci": "g7h6",
      "solutionSan": "gxh6",
      "motif": "capture",
      "theme": "gxh6 — tangkap (babak tengah)",
      "description": "Hitam menjawab dengan gxh6: pion Hitam mengambil menara bernilai 5 pion di h6 (selisih 4 poin). Posisi ini masuk hitungan taktik.",
      "hintPiece": "Pion di g7",
    },
    {
      "id": "p08",
      "category": "opening",
      "difficulty": "Sedang",
      "xp": 100,
      "track": "puzzle",
      "fen": "rnb1k2r/2pp1p2/p3pnp1/6qR/2p5/4P3/PP1P1PP1/RNB1KBN1 b Qkq - 0 11",
      "turn": "b",
      "solutionUci": "g6h5",
      "solutionSan": "gxh5",
      "motif": "capture",
      "theme": "gxh5 — tangkap (pembukaan)",
      "description": "Hitam menjawab dengan gxh5: pion Hitam mengambil menara bernilai 5 pion di h5 (selisih 4 poin). Posisi ini masuk hitungan taktik.",
      "hintPiece": "Pion di g6",
    },
    {
      "id": "p09",
      "category": "opening",
      "difficulty": "Sedang",
      "xp": 100,
      "track": "puzzle",
      "fen": "rnb1k2r/2pp1p2/p3pnp1/7R/2B5/4P3/PP1P1Pq1/RNB1K1N1 b Qkq - 0 12",
      "turn": "b",
      "solutionUci": "g6h5",
      "solutionSan": "gxh5",
      "motif": "capture",
      "theme": "gxh5 — tangkap (pembukaan)",
      "description": "Hitam menjawab dengan gxh5: pion Hitam mengambil menara bernilai 5 pion di h5 (selisih 4 poin). Posisi ini masuk hitungan taktik.",
      "hintPiece": "Pion di g6",
    },
    {
      "id": "p10",
      "category": "middlegame",
      "difficulty": "Sulit",
      "xp": 175,
      "track": "puzzle",
      "fen": "rnb1k2r/2pp1p2/B3pn2/7p/8/4P1q1/PP1P1P2/RNB1K1N1 w Qkq - 1 14",
      "turn": "w",
      "solutionUci": "f2g3",
      "solutionSan": "fxg3",
      "motif": "capture",
      "theme": "fxg3 — tangkap (babak tengah)",
      "description": "Putih menjawab dengan fxg3: pion Putih mengambil sekertaris bernilai 9 pion di g3 (selisih 8 poin). Posisi ini masuk hitungan taktik.",
      "hintPiece": "Pion di f2",
    },
    {
      "id": "p11",
      "category": "middlegame",
      "difficulty": "Sulit",
      "xp": 175,
      "track": "puzzle",
      "fen": "1nB1k2r/2pp1p2/4pn2/7p/8/4P1q1/rP1P1P2/RNB1K1N1 w Qk - 0 15",
      "turn": "w",
      "solutionUci": "f2g3",
      "solutionSan": "fxg3",
      "motif": "capture",
      "theme": "fxg3 — tangkap (babak tengah)",
      "description": "Putih menjawab dengan fxg3: pion Putih mengambil sekertaris bernilai 9 pion di g3 (selisih 8 poin). Posisi ini masuk hitungan taktik.",
      "hintPiece": "Pion di f2",
    },
    {
      "id": "p12",
      "category": "endgame",
      "difficulty": "Sedang",
      "xp": 100,
      "track": "puzzle",
      "fen": "5k2/2pp1B2/8/4r3/3n1P2/7r/1P1N4/2B1K3 w - - 0 33",
      "turn": "w",
      "solutionUci": "f4e5",
      "solutionSan": "fxe5",
      "motif": "capture",
      "theme": "fxe5 — tangkap (babak akhir)",
      "description": "Putih menjawab dengan fxe5: pion Putih mengambil menara bernilai 5 pion di e5 (selisih 4 poin). Posisi ini masuk hitungan taktik.",
      "hintPiece": "Pion di f4",
    },
    {
      "id": "p13",
      "category": "endgame",
      "difficulty": "Sedang",
      "xp": 100,
      "track": "puzzle",
      "fen": "6k1/3q3R/3p4/PP3p1P/p5b1/8/5P2/7K w - - 1 40",
      "turn": "w",
      "solutionUci": "h7d7",
      "solutionSan": "Rxd7",
      "motif": "capture",
      "theme": "Rxd7 — tangkap (babak akhir)",
      "description": "Putih menjawab dengan Rxd7: menara Putih mengambil sekertaris bernilai 9 pion di d7 (selisih 4 poin). Posisi ini masuk hitungan taktik.",
      "hintPiece": "Menara Putih",
    },
    {
      "id": "p14",
      "category": "endgame",
      "difficulty": "Mudah",
      "xp": 50,
      "track": "quest",
      "fen": "5k2/8/3p4/P4P1P/8/8/p7/7K b - - 1 49",
      "turn": "b",
      "solutionUci": "a2a1n",
      "solutionSan": "a1=N",
      "motif": "promotion",
      "theme": "a1=N — promosi pion (babak akhir)",
      "description": "Pion di a2 maju dan langsung promosi tanpa captures. Hitam menyelesaikan dengan a1=N dan mendapat perwira baru di a1.",
      "hintPiece": "Pion di a2",
    },
    {
      "id": "p15",
      "category": "endgame",
      "difficulty": "Mudah",
      "xp": 50,
      "track": "puzzle",
      "fen": "8/4k3/P2p4/5P1P/8/8/p7/7K b - - 0 50",
      "turn": "b",
      "solutionUci": "a2a1n",
      "solutionSan": "a1=N",
      "motif": "promotion",
      "theme": "a1=N — promosi pion (babak akhir)",
      "description": "Pion di a2 maju dan langsung promosi tanpa captures. Hitam menyelesaikan dengan a1=N dan mendapat perwira baru di a1.",
      "hintPiece": "Pion di a2",
    },
    {
      "id": "p16",
      "category": "endgame",
      "difficulty": "Sulit",
      "xp": 175,
      "track": "puzzle",
      "fen": "8/P5q1/7P/3p1Pk1/8/7K/8/8 w - - 3 61",
      "turn": "w",
      "solutionUci": "h6g7",
      "solutionSan": "hxg7",
      "motif": "capture",
      "theme": "hxg7 — tangkap (babak akhir)",
      "description": "Putih menjawab dengan hxg7: pion Putih mengambil sekertaris bernilai 9 pion di g7 (selisih 8 poin). Posisi ini masuk hitungan taktik.",
      "hintPiece": "Pion di h6",
    },
    {
      "id": "p17",
      "category": "endgame",
      "difficulty": "Mudah",
      "xp": 50,
      "track": "puzzle",
      "fen": "8/P7/7P/3p1Pk1/3q4/6K1/8/8 w - - 5 62",
      "turn": "w",
      "solutionUci": "a7a8n",
      "solutionSan": "a8=N",
      "motif": "promotion",
      "theme": "a8=N — promosi pion (babak akhir)",
      "description": "Pion di a7 maju dan langsung promosi tanpa captures. Putih menyelesaikan dengan a8=N dan mendapat perwira baru di a8.",
      "hintPiece": "Pion di a7",
    },
    {
      "id": "p18",
      "category": "middlegame",
      "difficulty": "Sedang",
      "xp": 100,
      "track": "quest",
      "fen": "r3k1n1/p2n1ppr/1p1p4/8/P7/1P6/3K1p2/R1B2BN1 b q - 0 17",
      "turn": "b",
      "solutionUci": "f2g1n",
      "solutionSan": "fxg1=N",
      "motif": "promotion",
      "theme": "fxg1=N — promosi pion (babak tengah)",
      "description": "Pion di f2 maju dan langsung promosi sambil menangkap knight bernilai 3 pion di g1. Hitam menyelesaikan dengan fxg1=N dan mendapat perwira baru di g1.",
      "hintPiece": "Pion di f2",
    },
    {
      "id": "p19",
      "category": "endgame",
      "difficulty": "Sedang",
      "xp": 100,
      "track": "puzzle",
      "fen": "4k3/2r5/BP4p1/5p2/1P3K2/8/8/6n1 w - - 2 35",
      "turn": "w",
      "solutionUci": "b6c7",
      "solutionSan": "bxc7",
      "motif": "capture",
      "theme": "bxc7 — tangkap (babak akhir)",
      "description": "Putih menjawab dengan bxc7: pion Putih mengambil menara bernilai 5 pion di c7 (selisih 4 poin). Posisi ini masuk hitungan taktik.",
      "hintPiece": "Pion di b6",
    },
    {
      "id": "p20",
      "category": "endgame",
      "difficulty": "Sedang",
      "xp": 100,
      "track": "puzzle",
      "fen": "4k3/r7/1P4p1/3B1pK1/1P6/8/8/6n1 w - - 10 39",
      "turn": "w",
      "solutionUci": "b6a7",
      "solutionSan": "bxa7",
      "motif": "capture",
      "theme": "bxa7 — tangkap (babak akhir)",
      "description": "Putih menjawab dengan bxa7: pion Putih mengambil menara bernilai 5 pion di a7 (selisih 4 poin). Posisi ini masuk hitungan taktik.",
      "hintPiece": "Pion di b6",
    },
    {
      "id": "p21",
      "category": "middlegame",
      "difficulty": "Sedang",
      "xp": 100,
      "track": "puzzle",
      "fen": "1nbk2r1/1p1p4/2npp3/5P1P/8/Q4K1P/rP1b1PR1/1R4N1 b - - 2 22",
      "turn": "b",
      "solutionUci": "a2a3",
      "solutionSan": "Rxa3+",
      "motif": "capture-check",
      "theme": "Rxa3+ — tangkap + skak (babak tengah)",
      "description": "Hitam menjawab dengan Rxa3+: menara Hitam mengambil sekertaris bernilai 9 pion di a3 (selisih 4 poin) dan langsung memberi skak. Putih tinggal 4 jawaban.",
      "hintPiece": "Menara Hitam",
    },
    {
      "id": "p22",
      "category": "opening",
      "difficulty": "Sedang",
      "xp": 100,
      "track": "puzzle",
      "fen": "2bq1bnr/2pkpppp/2np4/8/7P/r4P1N/1PPPP1P1/2BQKB1R w K - 0 8",
      "turn": "w",
      "solutionUci": "b2a3",
      "solutionSan": "bxa3",
      "motif": "capture",
      "theme": "bxa3 — tangkap (pembukaan)",
      "description": "Putih menjawab dengan bxa3: pion Putih mengambil menara bernilai 5 pion di a3 (selisih 4 poin). Posisi ini masuk hitungan taktik.",
      "hintPiece": "Pion di b2",
    },
    {
      "id": "p23",
      "category": "middlegame",
      "difficulty": "Mudah",
      "xp": 50,
      "track": "puzzle",
      "fen": "rn1k4/5pP1/p7/2p1p3/8/4P3/PP2KP2/RNB1b1N1 w - - 1 19",
      "turn": "w",
      "solutionUci": "g7g8n",
      "solutionSan": "g8=N",
      "motif": "promotion",
      "theme": "g8=N — promosi pion (babak tengah)",
      "description": "Pion di g7 maju dan langsung promosi tanpa captures. Putih menyelesaikan dengan g8=N dan mendapat perwira baru di g8.",
      "hintPiece": "Pion di g7",
    },
    {
      "id": "p24",
      "category": "opening",
      "difficulty": "Sedang",
      "xp": 100,
      "track": "puzzle",
      "fen": "r1b1k1nr/ppppq2p/5p2/8/5n2/NP6/P1PK1PPP/4RBNR w kq - 2 12",
      "turn": "w",
      "solutionUci": "e1e7",
      "solutionSan": "Rxe7+",
      "motif": "capture-check",
      "theme": "Rxe7+ — tangkap + skak (pembukaan)",
      "description": "Putih menjawab dengan Rxe7+: menara Putih mengambil sekertaris bernilai 9 pion di e7 (selisih 4 poin) dan langsung memberi skak. Hitam tinggal 4 jawaban.",
      "hintPiece": "Menara Putih",
    },
    {
      "id": "p25",
      "category": "opening",
      "difficulty": "Sulit",
      "xp": 175,
      "track": "puzzle",
      "fen": "rnbq1knr/pp3p1p/2pp4/P7/3b4/N1Q1P3/1P2BPP1/R1B1K1N1 b Q - 2 15",
      "turn": "b",
      "solutionUci": "d4c3",
      "solutionSan": "Bxc3+",
      "motif": "capture-check",
      "theme": "Bxc3+ — tangkap + skak (pembukaan)",
      "description": "Hitam menjawab dengan Bxc3+: gajah Hitam mengambil sekertaris bernilai 9 pion di c3 (selisih 6 poin) dan langsung memberi skak. Putih tinggal 4 jawaban.",
      "hintPiece": "Gajah Hitam",
    },
    {
      "id": "p26",
      "category": "middlegame",
      "difficulty": "Mudah",
      "xp": 50,
      "track": "puzzle",
      "fen": "5B2/1p1n1p1p/1p6/1N6/1n4P1/3k4/5P2/rN2K3 b - - 0 34",
      "turn": "b",
      "solutionUci": "a1b1",
      "solutionSan": "Rxb1#",
      "motif": "mate",
      "theme": "Rxb1# — skakmat (babak tengah)",
      "description": "Hitam menutup dengan Rxb1# dan itu langsung skakmat. Lawan tidak punya satu jawaban pun.",
      "hintPiece": "Menara Hitam",
    },
    {
      "id": "p27",
      "category": "middlegame",
      "difficulty": "Mudah",
      "xp": 50,
      "track": "puzzle",
      "fen": "2b5/1p1p3r/4k1pn/4p1qp/7P/2P2N1R/4PPP1/1NB1KB2 b - - 7 21",
      "turn": "b",
      "solutionUci": "g5c1",
      "solutionSan": "Qxc1#",
      "motif": "mate",
      "theme": "Qxc1# — skakmat (babak tengah)",
      "description": "Hitam menutup dengan Qxc1# dan itu langsung skakmat. Lawan tidak punya satu jawaban pun.",
      "hintPiece": "Sekertaris Hitam",
    },
    {
      "id": "p28",
      "category": "endgame",
      "difficulty": "Sulit",
      "xp": 175,
      "track": "puzzle",
      "fen": "3b4/8/3k1Q2/8/1p3P1p/1P1K4/1R1P4/1NB5 b - - 0 36",
      "turn": "b",
      "solutionUci": "d8f6",
      "solutionSan": "Bxf6",
      "motif": "capture",
      "theme": "Bxf6 — tangkap (babak akhir)",
      "description": "Hitam menjawab dengan Bxf6: gajah Hitam mengambil sekertaris bernilai 9 pion di f6 (selisih 6 poin). Posisi ini masuk hitungan taktik.",
      "hintPiece": "Gajah Hitam",
    },
    {
      "id": "p29",
      "category": "middlegame",
      "difficulty": "Mudah",
      "xp": 50,
      "track": "puzzle",
      "fen": "kr2Q3/p6p/5B1n/3p4/3P1P2/6P1/3N1P1P/4KBNR b K - 0 24",
      "turn": "b",
      "solutionUci": "b8e8",
      "solutionSan": "Rxe8+",
      "motif": "capture-check",
      "theme": "Rxe8+ — tangkap + skak (babak tengah)",
      "description": "Hitam menjawab dengan Rxe8+: menara Hitam mengambil sekertaris bernilai 9 pion di e8 (selisih 4 poin) dan langsung memberi skak. Putih tinggal 6 jawaban.",
      "hintPiece": "Menara Hitam",
    },
    {
      "id": "p30",
      "category": "middlegame",
      "difficulty": "Mudah",
      "xp": 50,
      "track": "puzzle",
      "fen": "6n1/4p3/rp2P1k1/p7/Pp1K1p2/8/4p2P/RN6 b - - 0 36",
      "turn": "b",
      "solutionUci": "e2e1n",
      "solutionSan": "e1=N",
      "motif": "promotion",
      "theme": "e1=N — promosi pion (babak tengah)",
      "description": "Pion di e2 maju dan langsung promosi tanpa captures. Hitam menyelesaikan dengan e1=N dan mendapat perwira baru di e1.",
      "hintPiece": "Pion di e2",
    },
    {
      "id": "p31",
      "category": "middlegame",
      "difficulty": "Mudah",
      "xp": 50,
      "track": "puzzle",
      "fen": "6n1/4p3/rp2P2k/p7/PpK2p2/8/4p2P/RN6 b - - 2 37",
      "turn": "b",
      "solutionUci": "e2e1n",
      "solutionSan": "e1=N",
      "motif": "promotion",
      "theme": "e1=N — promosi pion (babak tengah)",
      "description": "Pion di e2 maju dan langsung promosi tanpa captures. Hitam menyelesaikan dengan e1=N dan mendapat perwira baru di e1.",
      "hintPiece": "Pion di e2",
    },
    {
      "id": "p32",
      "category": "opening",
      "difficulty": "Mudah",
      "xp": 50,
      "track": "quest",
      "fen": "r1b1k1nr/1ppp2pp/p1n1p3/8/7q/2N3P1/PPPPP3/R1BQKB1R b KQkq - 1 8",
      "turn": "b",
      "solutionUci": "h4g3",
      "solutionSan": "Qxg3#",
      "motif": "mate",
      "theme": "Qxg3# — skakmat (pembukaan)",
      "description": "Hitam menutup dengan Qxg3# dan itu langsung skakmat. Lawan tidak punya satu jawaban pun.",
      "hintPiece": "Sekertaris Hitam",
    },
    {
      "id": "p33",
      "category": "opening",
      "difficulty": "Mudah",
      "xp": 50,
      "track": "puzzle",
      "fen": "r1b3nr/1pppk1pp/p1n1p3/8/7q/1PN3P1/P1PPP3/R1BQKB1R b KQ - 0 9",
      "turn": "b",
      "solutionUci": "h4g3",
      "solutionSan": "Qxg3#",
      "motif": "mate",
      "theme": "Qxg3# — skakmat (pembukaan)",
      "description": "Hitam menutup dengan Qxg3# dan itu langsung skakmat. Lawan tidak punya satu jawaban pun.",
      "hintPiece": "Sekertaris Hitam",
    },
    {
      "id": "p34",
      "category": "endgame",
      "difficulty": "Mudah",
      "xp": 50,
      "track": "puzzle",
      "fen": "6k1/2p5/p3b3/4B1P1/7K/Pr6/8/8 b - - 0 39",
      "turn": "b",
      "solutionUci": "b3h3",
      "solutionSan": "Rh3#",
      "motif": "mate",
      "theme": "Rh3# — skakmat (babak akhir)",
      "description": "Hitam menutup dengan Rh3# dan itu langsung skakmat. Lawan tidak punya satu jawaban pun.",
      "hintPiece": "Menara Hitam",
    },
    {
      "id": "p35",
      "category": "opening",
      "difficulty": "Mudah",
      "xp": 50,
      "track": "puzzle",
      "fen": "r3kb1r/pp1b2pp/5p2/4P3/2q3n1/4P3/PPnPN1PP/R1BK1B1R b kq - 0 12",
      "turn": "b",
      "solutionUci": "g4f2",
      "solutionSan": "Nf2#",
      "motif": "mate",
      "theme": "Nf2# — skakmat (pembukaan)",
      "description": "Hitam menutup dengan Nf2# dan itu langsung skakmat. Lawan tidak punya satu jawaban pun.",
      "hintPiece": "Knight Hitam",
    },
    {
      "id": "p36",
      "category": "middlegame",
      "difficulty": "Mudah",
      "xp": 50,
      "track": "puzzle",
      "fen": "rnb5/p1qppk2/1p5B/2p5/P1P2P2/1P4n1/3PP3/RN1QKB1r b Q - 2 16",
      "turn": "b",
      "solutionUci": "h1f1",
      "solutionSan": "Rxf1#",
      "motif": "mate",
      "theme": "Rxf1# — skakmat (babak tengah)",
      "description": "Hitam menutup dengan Rxf1# dan itu langsung skakmat. Lawan tidak punya satu jawaban pun.",
      "hintPiece": "Menara Hitam",
    },
    {
      "id": "p37",
      "category": "middlegame",
      "difficulty": "Mudah",
      "xp": 50,
      "track": "puzzle",
      "fen": "rnb5/p1qppk2/1p5B/P1p5/2P2P2/1P4n1/3PP3/RN1QKBr1 b Q - 0 17",
      "turn": "b",
      "solutionUci": "g1f1",
      "solutionSan": "Rxf1#",
      "motif": "mate",
      "theme": "Rxf1# — skakmat (babak tengah)",
      "description": "Hitam menutup dengan Rxf1# dan itu langsung skakmat. Lawan tidak punya satu jawaban pun.",
      "hintPiece": "Menara Hitam",
    },
    {
      "id": "p38",
      "category": "middlegame",
      "difficulty": "Sedang",
      "xp": 100,
      "track": "puzzle",
      "fen": "4rb1r/p1p1kppp/2np4/6P1/2Np4/5N1Q/Pp2PK1P/R1B4R b - - 1 18",
      "turn": "b",
      "solutionUci": "b2a1n",
      "solutionSan": "bxa1=N",
      "motif": "promotion",
      "theme": "bxa1=N — promosi pion (babak tengah)",
      "description": "Pion di b2 maju dan langsung promosi sambil menangkap menara bernilai 5 pion di a1. Hitam menyelesaikan dengan bxa1=N dan mendapat perwira baru di a1.",
      "hintPiece": "Pion di b2",
    },
    {
      "id": "p39",
      "category": "middlegame",
      "difficulty": "Sedang",
      "xp": 100,
      "track": "puzzle",
      "fen": "r4b2/p1p2kP1/3pp3/6B1/3p4/1P6/1N2PK1R/R5N1 w - - 1 27",
      "turn": "w",
      "solutionUci": "g7f8n",
      "solutionSan": "gxf8=N",
      "motif": "promotion",
      "theme": "gxf8=N — promosi pion (babak tengah)",
      "description": "Pion di g7 maju dan langsung promosi sambil menangkap gajah bernilai 3 pion di f8. Putih menyelesaikan dengan gxf8=N dan mendapat perwira baru di f8.",
      "hintPiece": "Pion di g7",
    },
    {
      "id": "p40",
      "category": "middlegame",
      "difficulty": "Sedang",
      "xp": 100,
      "track": "puzzle",
      "fen": "r4b2/p4kP1/2ppp3/6B1/3p4/1P6/1N2P2R/R3K1N1 w - - 0 28",
      "turn": "w",
      "solutionUci": "g7f8n",
      "solutionSan": "gxf8=N",
      "motif": "promotion",
      "theme": "gxf8=N — promosi pion (babak tengah)",
      "description": "Pion di g7 maju dan langsung promosi sambil menangkap gajah bernilai 3 pion di f8. Putih menyelesaikan dengan gxf8=N dan mendapat perwira baru di f8.",
      "hintPiece": "Pion di g7",
    },
    {
      "id": "p41",
      "category": "opening",
      "difficulty": "Mudah",
      "xp": 50,
      "track": "puzzle",
      "fen": "rn2kb1r/2pp1q2/bp2p1pp/p7/3PK3/1P2P3/P1P3PP/RNBQR1N1 b kq - 7 14",
      "turn": "b",
      "solutionUci": "f7f5",
      "solutionSan": "Qf5#",
      "motif": "mate",
      "theme": "Qf5# — skakmat (pembukaan)",
      "description": "Hitam menutup dengan Qf5# dan itu langsung skakmat. Lawan tidak punya satu jawaban pun.",
      "hintPiece": "Sekertaris Hitam",
    },
    {
      "id": "p42",
      "category": "opening",
      "difficulty": "Mudah",
      "xp": 50,
      "track": "puzzle",
      "fen": "rnbk1bnr/p3p3/1p1q2p1/6pp/8/2P4P/PP2PPP1/3RKBNR w K - 2 13",
      "turn": "w",
      "solutionUci": "d1d6",
      "solutionSan": "Rxd6+",
      "motif": "capture-check",
      "theme": "Rxd6+ — tangkap + skak (pembukaan)",
      "description": "Putih menjawab dengan Rxd6+: menara Putih mengambil sekertaris bernilai 9 pion di d6 (selisih 4 poin) dan langsung memberi skak. Hitam tinggal 5 jawaban.",
      "hintPiece": "Menara Putih",
    },
    {
      "id": "p43",
      "category": "middlegame",
      "difficulty": "Sulit",
      "xp": 175,
      "track": "puzzle",
      "fen": "2b1k1nr/1ppp4/r1n2ppp/p3Q3/5KP1/5P2/PPPP4/1RB2B2 b k - 0 18",
      "turn": "b",
      "solutionUci": "f6e5",
      "solutionSan": "fxe5+",
      "motif": "capture-check",
      "theme": "fxe5+ — tangkap + skak (babak tengah)",
      "description": "Hitam menjawab dengan fxe5+: pion Hitam mengambil sekertaris bernilai 9 pion di e5 (selisih 8 poin) dan langsung memberi skak. Putih tinggal 3 jawaban.",
      "hintPiece": "Pion di f6",
    },
    {
      "id": "p44",
      "category": "opening",
      "difficulty": "Mudah",
      "xp": 50,
      "track": "puzzle",
      "fen": "rn1qkbnr/pp1bp3/6p1/2p2p1Q/8/3KP1P1/PPP2P1P/RNB2BNR w kq - 0 8",
      "turn": "w",
      "solutionUci": "h5g6",
      "solutionSan": "Qxg6#",
      "motif": "mate",
      "theme": "Qxg6# — skakmat (pembukaan)",
      "description": "Putih menutup dengan Qxg6# dan itu langsung skakmat. Lawan tidak punya satu jawaban pun.",
      "hintPiece": "Sekertaris Putih",
    },
    {
      "id": "p45",
      "category": "opening",
      "difficulty": "Mudah",
      "xp": 50,
      "track": "puzzle",
      "fen": "r1b1kb1r/pp4pB/n2p4/2p1p3/P6q/2N3P1/1PPPPP2/R1BQ1K1R b - - 0 12",
      "turn": "b",
      "solutionUci": "h4h1",
      "solutionSan": "Qxh1#",
      "motif": "mate",
      "theme": "Qxh1# — skakmat (pembukaan)",
      "description": "Hitam menutup dengan Qxh1# dan itu langsung skakmat. Lawan tidak punya satu jawaban pun.",
      "hintPiece": "Sekertaris Hitam",
    },
    {
      "id": "p46",
      "category": "middlegame",
      "difficulty": "Mudah",
      "xp": 50,
      "track": "puzzle",
      "fen": "6n1/p2p2r1/5p1p/P6P/4PP2/3PP2R/R5B1/K5k1 w - - 6 39",
      "turn": "w",
      "solutionUci": "h3h1",
      "solutionSan": "Rh1#",
      "motif": "mate",
      "theme": "Rh1# — skakmat (babak tengah)",
      "description": "Putih menutup dengan Rh1# dan itu langsung skakmat. Lawan tidak punya satu jawaban pun.",
      "hintPiece": "Menara Putih",
    },
    {
      "id": "p47",
      "category": "opening",
      "difficulty": "Mudah",
      "xp": 50,
      "track": "puzzle",
      "fen": "1rb2bnN/p1p3p1/3pk2p/2p2p1Q/5P2/4P1P1/PPP1K2P/RNB3R1 w - - 2 15",
      "turn": "w",
      "solutionUci": "h5f7",
      "solutionSan": "Qf7#",
      "motif": "mate",
      "theme": "Qf7# — skakmat (pembukaan)",
      "description": "Putih menutup dengan Qf7# dan itu langsung skakmat. Lawan tidak punya satu jawaban pun.",
      "hintPiece": "Sekertaris Putih",
    },
    {
      "id": "p48",
      "category": "middlegame",
      "difficulty": "Sedang",
      "xp": 100,
      "track": "puzzle",
      "fen": "3rk3/pp2Pp2/8/P1pp4/7P/5K2/8/RNB1R3 w - - 0 26",
      "turn": "w",
      "solutionUci": "e7d8n",
      "solutionSan": "exd8=N+",
      "motif": "promotion",
      "theme": "exd8=N+ — promosi pion (babak tengah)",
      "description": "Pion di e7 maju dan langsung promosi sambil menangkap menara bernilai 5 pion di d8. Putih menyelesaikan dengan exd8=N+ dan mendapat perwira baru di d8.",
      "hintPiece": "Pion di e7",
    },
    {
      "id": "p49",
      "category": "middlegame",
      "difficulty": "Sedang",
      "xp": 100,
      "track": "puzzle",
      "fen": "4k1r1/p1p4P/1p6/3rP1K1/P7/R7/1P6/1N6 w - - 2 32",
      "turn": "w",
      "solutionUci": "h7g8n",
      "solutionSan": "hxg8=N",
      "motif": "promotion",
      "theme": "hxg8=N — promosi pion (babak tengah)",
      "description": "Pion di h7 maju dan langsung promosi sambil menangkap menara bernilai 5 pion di g8. Putih menyelesaikan dengan hxg8=N dan mendapat perwira baru di g8.",
      "hintPiece": "Pion di h7",
    },
    {
      "id": "p50",
      "category": "opening",
      "difficulty": "Mudah",
      "xp": 50,
      "track": "puzzle",
      "fen": "rnbk1bnr/1p1pp1pp/p7/2p5/P7/1P4PP/2qPPP2/RNB1KBNR b KQ - 0 8",
      "turn": "b",
      "solutionUci": "c2c1",
      "solutionSan": "Qxc1#",
      "motif": "mate",
      "theme": "Qxc1# — skakmat (pembukaan)",
      "description": "Hitam menutup dengan Qxc1# dan itu langsung skakmat. Lawan tidak punya satu jawaban pun.",
      "hintPiece": "Sekertaris Hitam",
    },
] as Puzzle[];

/** Tab filter diturunkan dari data, jadi tidak pernah ada kategori kosong. */
export const PUZZLE_CATEGORIES: { id: PuzzleCategory | "all"; label: string }[] = [
  {
    "id": "all",
    "label": "Semua"
  },
  {
    "id": "endgame",
    "label": "Babak akhir"
  },
  {
    "id": "middlegame",
    "label": "Babak tengah"
  },
  {
    "id": "opening",
    "label": "Pembukaan"
  }
];

/** Bab Belajar & Quest memakai teka-teki yang sama: satu sumber, dua tampilan. */
export const QUEST_CHAPTERS: Puzzle[] = PUZZLES.filter((p) => p.track === "quest");

/** Teka-teki yang disimpan pemain dari pertandingan live (lihat lib/puzzle-store). */
export type SavedPuzzle = Puzzle & { savedAt: string; source: string };

export function byCategory(all: Puzzle[], category: PuzzleCategory | "all"): Puzzle[] {
  return category === "all" ? all : all.filter((p) => p.category === category);
}
