// AUTO-GENERATED oleh scripts/make_all_puzzles.js. JANGAN diedit manual.
// Teka-Teki Catur Terverifikasi (chess.js) berdasarkan Master Motifs Maxim Blokh (CT-Art 4.0),
// Buku Pintar Catur-Pedia (Fienso Suharsono), dan Terminologi Catur Standar Bahasa Indonesia.

export type PuzzleCategory = "opening" | "defense" | "middlegame" | "endgame" | "jebakan" | "skakmat" | "opponent";
export type PuzzleDifficulty = "Mudah" | "Sedang" | "Sulit";
export type PuzzleMotif = "mate" | "promotion" | "capture" | "capture-check" | "check" | "tactic" | "trap";
export type PuzzleTrack = "quest" | "puzzle";
export type PuzzleSource = "ct-art" | "bpcaturpedia" | "live";

export type Puzzle = {
  id: string;
  category: PuzzleCategory;
  difficulty: PuzzleDifficulty;
  track: PuzzleTrack;
  fen: string;
  turn: "w" | "b";
  solutionUci: string;
  solutionSan: string;
  motif: PuzzleMotif;
  theme: string;
  description: string;
  hintPiece: string;
  hintExplanation: string;
  trickExplanation: string;
  xp: number;
  source?: PuzzleSource;
};

export const PUZZLE_CATEGORIES: { id: PuzzleCategory | "all"; label: string }[] = [
  { id: "all", label: "Semua Kategori" },
  { id: "opening", label: "Pembukaan (Opening)" },
  { id: "defense", label: "Pertahanan (Defense)" },
  { id: "middlegame", label: "Babak Tengah (Middlegame)" },
  { id: "endgame", label: "Babak Akhir (Endgame)" },
  { id: "jebakan", label: "Jebakan (Traps) · BPCaturPedia" },
  { id: "skakmat", label: "Taktik Skakmat · BPCaturPedia" },
  { id: "opponent", label: "Trik Lawan Live" },
];

export function byCategory(puzzles: Puzzle[], category: PuzzleCategory | "all"): Puzzle[] {
  if (category === "all") return puzzles;
  return puzzles.filter((p) => p.category === category);
}

export const QUEST_CHAPTERS: Puzzle[] = [
  {
    "id": "p01",
    "category": "opening",
    "difficulty": "Mudah",
    "track": "quest",
    "fen": "r1bqkb1r/pppp1ppp/2n5/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 0 4",
    "turn": "w",
    "solutionUci": "h5f7",
    "solutionSan": "Qxf7#",
    "motif": "mate",
    "theme": "Skakmat Scholar (Scholar's Mate)",
    "description": "Manfaatkan titik lemah f7 yang hanya dijaga oleh Raja Hitam di awal pembukaan.",
    "hintPiece": "Menteri putih di h5.",
    "hintExplanation": "Menteri memukul bidak di f7 dengan perlindungan Gajah c4 untuk skakmat langsung.",
    "trickExplanation": "Tips Blokh: Titik f7/f2 sebelum rokade adalah titik terlemah di papan karena hanya dilindungi Raja.",
    "xp": 50
  },
  {
    "id": "p02",
    "category": "opening",
    "difficulty": "Mudah",
    "track": "quest",
    "fen": "rnbqkbnr/ppppp1pp/5p2/8/4P3/6P1/PPPP1P1P/RNBQKBNR w KQkq - 0 2",
    "turn": "w",
    "solutionUci": "d1h5",
    "solutionSan": "Qh5+",
    "motif": "check",
    "theme": "Celah Diagonal Maut (Fool's Pattern)",
    "description": "Hitam melangkahkan f6 di langkah pembuka. Manfaatkan celah diagonal e8-h5.",
    "hintPiece": "Menteri putih di d1.",
    "hintExplanation": "Luncurkan Menteri ke h5 untuk memberikan skak keras pada raja Hitam.",
    "trickExplanation": "Tips Blokh: Memajukan pion-f terlalu dini merusak benteng pertahanan diagonal Raja secara permanen.",
    "xp": 50
  },
  {
    "id": "p03",
    "category": "opening",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "r1bqkb1r/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 2 4",
    "turn": "w",
    "solutionUci": "f3g5",
    "solutionSan": "Ng5",
    "motif": "tactic",
    "theme": "Giuoco Piano: Taktik Italia Serangan Titik Lemah f7",
    "description": "Dalam Pembukaan Italia (Giuoco Piano C50-C54), titik f7 adalah titik terlemah Hitam sebelum rokade. Luncurkan Kuda f3 ke g5 berkolaborasi dengan Gajah c4 untuk melancarkan serangan ganda ke f7!",
    "hintPiece": "Kuda putih di f3.",
    "hintExplanation": "Langkahkan Kuda f3 ke g5 untuk menambah ancaman ganda ke petak f7.",
    "trickExplanation": "Taktik Italia (Giuoco Piano): Koordinasi Gajah c4 + Kuda g5 mengeksploitasi titik terlemah f7 sebelum Raja Hitam sempat mengamankan diri lewat rokade.",
    "xp": 100
  },
  {
    "id": "p04",
    "category": "opening",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 4",
    "turn": "b",
    "solutionUci": "f6e4",
    "solutionSan": "Nxe4",
    "motif": "capture",
    "theme": "Garpu Pusat Kuda (Center Fork Trick)",
    "description": "Hitam memukul pion e4 untuk merebut inisiatif pusat lewat garpuan d7-d5 pada langkah berikutnya.",
    "hintPiece": "Kuda hitam di f6.",
    "hintExplanation": "Pukul pion e4 dengan Kuda hitam.",
    "trickExplanation": "Tips Blokh: Jika Putih membalas Nxe4, Hitam melangkah d7-d5 menggarpu Gajah dan Kuda putih.",
    "xp": 100
  },
  {
    "id": "p05",
    "category": "opening",
    "difficulty": "Sulit",
    "track": "quest",
    "fen": "r2qkb1r/pp1n1ppp/2p5/4N3/2B1P3/8/PPPP1PPP/RNBbK2R w KQkq - 0 8",
    "turn": "w",
    "solutionUci": "c4f7",
    "solutionSan": "Bxf7+",
    "motif": "capture-check",
    "theme": "Jebakan Legal (Legal's Trap Finale)",
    "description": "Hitam tergiur memakan Menteri Putih di d1. Hukum kecerobohan lawan dengan skak pengorbanan gajah!",
    "hintPiece": "Gajah putih di c4.",
    "hintExplanation": "Pukul bidak f7 dengan Gajah untuk skak dan memaksa Raja Hitam melangkah ke e7.",
    "trickExplanation": "Tips Blokh (Decoy & Attraction): Korbankan perwira berharga untuk menarik Raja lawan ke jaring skakmat.",
    "xp": 175
  },
  {
    "id": "p06",
    "category": "opening",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "r1bqkb1r/pp1npppp/2p2n2/8/3PN3/8/PPP1QPPP/R1B1KBNR w KQkq - 1 6",
    "turn": "w",
    "solutionUci": "e4d6",
    "solutionSan": "Nd6#",
    "motif": "mate",
    "theme": "Skakmat Tercekik Caro-Kann",
    "description": "Hitam memblokir petak pelarian raja. Manfaatkan pin mutlak Menteri e2 terhadap pion e7!",
    "hintPiece": "Kuda putih di e4.",
    "hintExplanation": "Lompatkan Kuda ke d6 untuk skakmat mutlak karena pion e7 ter-pin oleh Menteri e2.",
    "trickExplanation": "Tips Blokh (Pinning Exploitation): Bidak yang ter-pin tidak mampu menjalankan fungsinya menjaga petak.",
    "xp": 100
  },
  {
    "id": "p07",
    "category": "opening",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "r1b1k2r/ppppqppp/2n5/4n3/1PP5/5N2/1P1NPPPP/R2QKB1R b KQkq - 0 8",
    "turn": "b",
    "solutionUci": "e5d3",
    "solutionSan": "Nd3#",
    "motif": "mate",
    "theme": "Skakmat Budapest Gambit",
    "description": "Putih lengah memakan perwira di b4. Luncurkan Kuda hitam untuk menyelesaikan duel seketika!",
    "hintPiece": "Kuda hitam di e5.",
    "hintExplanation": "Lompatkan Kuda ke d3 untuk skakmat karena pion e2 ter-pin oleh Menteri e7.",
    "trickExplanation": "Tips Blokh: Manfaatkan lajur semi-terbuka untuk memaku bidak penjaga raja.",
    "xp": 100
  },
  {
    "id": "p08",
    "category": "opening",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "r1bqkb1r/pppn1ppp/5n2/3N2B1/3P4/8/PP2PPPP/R2QKBNR b KQkq - 0 6",
    "turn": "b",
    "solutionUci": "f6d5",
    "solutionSan": "Nxd5",
    "motif": "capture",
    "theme": "Jebakan Gajah Queen's Gambit (Elephant Trap)",
    "description": "Putih baru saja memukul d5 dengan Kuda. Balas dengan memukul kuda tersebut!",
    "hintPiece": "Kuda hitam di f6.",
    "hintExplanation": "Pukul Kuda d5 dengan Kuda f6. Jika Putih memakan menteri d8, Hitam membalas Bb4+!",
    "trickExplanation": "Tips Blokh: Umpan semu (Pseudo-sacrifice) yang memicu skakmat atau perolehan perwira kembali.",
    "xp": 100
  },
  {
    "id": "p09",
    "category": "opening",
    "difficulty": "Mudah",
    "track": "quest",
    "fen": "rnbqkbnr/pppp1ppp/8/4p3/4PP2/8/PPPP2PP/RNBQKBNR b KQkq - 0 2",
    "turn": "b",
    "solutionUci": "d8h4",
    "solutionSan": "Qh4+",
    "motif": "check",
    "theme": "Skak Serangan Balik King's Gambit",
    "description": "Putih membuka jalur sayap raja f2-f4 secara terburu-buru. Balas dengan serangan cepat!",
    "hintPiece": "Menteri hitam di d8.",
    "hintExplanation": "Langkahkan Menteri ke h4 untuk memberikan skak keras pada raja putih.",
    "trickExplanation": "Tips Blokh: Jangan membuka jalur sayap raja tanpa kalkulasi perlindungan raja yang matang.",
    "xp": 50
  },
  {
    "id": "p10",
    "category": "opening",
    "difficulty": "Sulit",
    "track": "quest",
    "fen": "r1b1kbnr/pppp1ppp/8/4n3/3PP2q/8/PPP2PPP/RNBQKBNR w KQkq - 1 5",
    "turn": "w",
    "solutionUci": "d4e5",
    "solutionSan": "dxe5",
    "motif": "capture",
    "theme": "Menghukum Manuver Menteri Terlalu Dini",
    "description": "Hitam melancarkan serangan menteri prematur dan meninggalkan Kuda di e5 tanpa perlindungan.",
    "hintPiece": "Pion putih di d4.",
    "hintExplanation": "Pukul Kuda hitam di e5 secara gratis dengan pion d4.",
    "trickExplanation": "Tips Blokh: Mengabaikan perkembangan perwira demi serangan menteri solo berujung kehilangan material.",
    "xp": 175
  },
  {
    "id": "p11",
    "category": "opening",
    "difficulty": "Mudah",
    "track": "quest",
    "fen": "r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 4 5",
    "turn": "w",
    "solutionUci": "e1g1",
    "solutionSan": "O-O",
    "motif": "tactic",
    "theme": "Rokade Dini Mengamankan Raja",
    "description": "Selesaikan tahap pembukaan dengan mengamankan Raja di sudut dan mengaktifkan Benteng.",
    "hintPiece": "Raja putih di e1.",
    "hintExplanation": "Lakukan rokade sayap raja (O-O) untuk menuntaskan koordinasi pertahanan.",
    "trickExplanation": "Tips Blokh: King safety adalah syarat utama sebelum melancarkan operasi taktis agresif.",
    "xp": 50
  },
  {
    "id": "p12",
    "category": "opening",
    "difficulty": "Sulit",
    "track": "quest",
    "fen": "r1bqk2r/pppp1ppp/2n5/1B2p3/4n3/5N2/PPPP1PPP/RNBQR1K1 w kq - 0 6",
    "turn": "w",
    "solutionUci": "e1e4",
    "solutionSan": "Rxe4",
    "motif": "capture",
    "theme": "Eksploitasi Pin Terbuka Ruy Lopez",
    "description": "Kuda Hitam di e4 berada pada jalur terbuka raja e8. Ambil keunggulan material!",
    "hintPiece": "Benteng putih di e1.",
    "hintExplanation": "Pukul Kuda di e4 dengan Benteng e1.",
    "trickExplanation": "Tips Blokh: Benteng di lajur terbuka vertikal langsung mengeksploitasi perwira di depan raja.",
    "xp": 175
  },
  {
    "id": "p25",
    "category": "endgame",
    "difficulty": "Mudah",
    "track": "quest",
    "fen": "8/5k2/8/8/8/8/4P3/4K3 w - - 0 1",
    "turn": "w",
    "solutionUci": "e1d2",
    "solutionSan": "Kd2",
    "motif": "tactic",
    "theme": "Oposisi Raja Membimbing Pion",
    "description": "Aktifkan Raja untuk mengawal pion maju menuju petak promosi.",
    "hintPiece": "Raja putih di e1.",
    "hintExplanation": "Langkahkan Raja ke d2.",
    "trickExplanation": "Tips Blokh (King Opposition): Di babak akhir, Raja adalah perwira penyerang utama pembuka jalan pion.",
    "xp": 50
  },
  {
    "id": "p26",
    "category": "endgame",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "8/8/8/8/4k3/4p3/4K3/8 w - - 0 1",
    "turn": "w",
    "solutionUci": "e2e1",
    "solutionSan": "Ke1",
    "motif": "tactic",
    "theme": "Pertahanan Oposisi Menahan Pion Lawan",
    "description": "Pion Hitam di e3. Mundurkan Raja putih ke petak e1 tepat di depan pion lawan untuk menahan remis.",
    "hintPiece": "Raja putih di e2.",
    "hintExplanation": "Mundurkan Raja ke e1.",
    "trickExplanation": "Tips Blokh (Endgame Opposition): Mundur lurus di depan pion lawan untuk merebut oposisi saat Raja lawan maju.",
    "xp": 100
  },
  {
    "id": "p27",
    "category": "endgame",
    "difficulty": "Sulit",
    "track": "quest",
    "fen": "8/4P3/8/8/8/5k2/8/4K3 w - - 0 1",
    "turn": "w",
    "solutionUci": "e7e8q",
    "solutionSan": "e8=Q",
    "motif": "promotion",
    "theme": "Promosi Menteri Penentu Kemenangan",
    "description": "Pion Putih di e7 siap promosi menjadi Menteri baru!",
    "hintPiece": "Pion putih di e7.",
    "hintExplanation": "Dorong pion ke e8 dan promosikan menjadi Menteri (Q).",
    "trickExplanation": "Tips Blokh (Pawn Breakthrough): Perhitungan langkah pion menuju baris ke-8 adalah fondasi kemenangan endgame.",
    "xp": 175
  },
  {
    "id": "p28",
    "category": "endgame",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "4k3/R7/8/8/8/8/8/4K3 w - - 0 1",
    "turn": "w",
    "solutionUci": "a7h7",
    "solutionSan": "Rh7",
    "motif": "tactic",
    "theme": "Memotong Jalur Raja Lawan (Rook Cut)",
    "description": "Kunci Raja hitam di baris ke-8 dengan menggeser Benteng di baris ke-7.",
    "hintPiece": "Benteng putih di a7.",
    "hintExplanation": "Geser Benteng ke h7.",
    "trickExplanation": "Tips Blokh (7th Rank Domination): Benteng di baris ke-7 mengurung Raja lawan dan memutus mobilitasnya.",
    "xp": 100
  },
  {
    "id": "p29",
    "category": "endgame",
    "difficulty": "Mudah",
    "track": "quest",
    "fen": "8/8/8/8/8/4k3/R7/4K3 w - - 0 1",
    "turn": "w",
    "solutionUci": "a2a3",
    "solutionSan": "Ra3+",
    "motif": "check",
    "theme": "Skak Pemutus Oposisi",
    "description": "Gunakan Benteng untuk memberi skak horizontal dan memaksa Raja lawan mundur.",
    "hintPiece": "Benteng putih di a2.",
    "hintExplanation": "Langkahkan Benteng ke a3 untuk memberi skak.",
    "trickExplanation": "Tips Blokh: Skak horizontal memisahkan Raja musuh dari perlindungan pion.",
    "xp": 50
  },
  {
    "id": "p30",
    "category": "endgame",
    "difficulty": "Sulit",
    "track": "quest",
    "fen": "8/8/8/8/8/5k2/7p/5K2 b - - 0 1",
    "turn": "b",
    "solutionUci": "h2h1q",
    "solutionSan": "h1=Q#",
    "motif": "mate",
    "theme": "Skakmat Promosi Sudut",
    "description": "Pion h2 melangkah ke h1 dan promosi menjadi Menteri untuk skakmat seketika!",
    "hintPiece": "Pion hitam di h2.",
    "hintExplanation": "Dorong pion ke h1 dan jadikan Menteri (Q#).",
    "trickExplanation": "Tips Blokh: Promosi dengan tempo skakmat menyudahi duel seketika tanpa perlawanan.",
    "xp": 175
  },
  {
    "id": "p31",
    "category": "middlegame",
    "difficulty": "Sulit",
    "track": "quest",
    "fen": "3r2k1/p4ppp/1p6/8/8/8/PP3PPP/3RR1K1 w - - 0 1",
    "turn": "w",
    "solutionUci": "d1d8",
    "solutionSan": "Rxd8#",
    "motif": "mate",
    "theme": "Skakmat Koridor Baris Belakang (Back-Rank Mate)",
    "description": "Benteng Hitam di d8 tidak memiliki perlindungan pendukung dan baris ke-8 terkunci oleh pionnya sendiri.",
    "hintPiece": "Benteng putih di d1.",
    "hintExplanation": "Pukul Benteng d8 dengan Benteng d1 untuk skakmat mutlak.",
    "trickExplanation": "Tips Blokh (Back-Rank Exploitation): Selalu waspadai ketiadaan petak pelarian (luft) pada baris belakang lawan.",
    "xp": 175
  },
  {
    "id": "p32",
    "category": "middlegame",
    "difficulty": "Sulit",
    "track": "quest",
    "fen": "r1b2rk1/pp3ppp/2n1p3/2qpP3/8/3B1N2/PPP2PPP/R2Q1RK1 w - - 0 12",
    "turn": "w",
    "solutionUci": "d3h7",
    "solutionSan": "Bxh7+",
    "motif": "capture-check",
    "theme": "Pengorbanan Klasik Greek Gift (Bxh7+)",
    "description": "Hancurkan perisai pion h7 raja Hitam untuk membuka jaring serangan Kuda Ng5+ dan Menteri Qh5!",
    "hintPiece": "Gajah putih di d3.",
    "hintExplanation": "Pukul pion h7 dengan Gajah untuk skak dan membongkar tempat persembunyian raja.",
    "trickExplanation": "Tips Blokh (Demolition of King Cover): Pengorbanan Gajah di h7 adalah senjata taktis utama menghadapi rokade pendek.",
    "xp": 175
  },
  {
    "id": "p33",
    "category": "middlegame",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "r4rk1/pp1b1ppp/1qn1p3/3p4/8/1P1B1N2/P1P2PPP/R2QR1K1 w - - 0 14",
    "turn": "w",
    "solutionUci": "d3h7",
    "solutionSan": "Bxh7+",
    "motif": "capture-check",
    "theme": "Colle System: Serangan Greek Gift (Bxh7+)",
    "description": "Dalam Colle System (D05), formasi piramida d4-e3 dan dorongan e4 membuka diagonal Gajah d3 lurus ke sayap raja Hitam. Korbankan Gajah di h7 untuk membongkar pertahanan rokade lawan!",
    "hintPiece": "Gajah putih di d3.",
    "hintExplanation": "Pukul pion h7 dengan Gajah putih untuk membuka posisi Raja lawan.",
    "trickExplanation": "Taktik Colle System: Pengorbanan Gajah h7 (Greek Gift) adalah trik utama Colle saat Kuda lawan tak lagi mengawal petak f6.",
    "xp": 100
  },
  {
    "id": "p34",
    "category": "middlegame",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "r1b1k2r/ppppqppp/2n5/4n3/1bP5/5N2/PP1NPPPP/R1BQKB1R w KQkq - 0 7",
    "turn": "w",
    "solutionUci": "a2a3",
    "solutionSan": "a3",
    "motif": "tactic",
    "theme": "Pengusiran Gajah Pengganggu",
    "description": "Gajah b4 menekan perwira putih. Usir segera dengan dorongan pion a3!",
    "hintPiece": "Pion putih di a2.",
    "hintExplanation": "Langkahkan pion ke a3 untuk mengancam Gajah b4.",
    "trickExplanation": "Tips Blokh: Kembalikan inisiatif dengan menyerang perwira depan lawan.",
    "xp": 100
  },
  {
    "id": "p35",
    "category": "defense",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "r1bqk2r/ppp2ppp/2n5/3np3/1b6/2PP1N2/PP1BBPPP/RN1QK2R b KQkq - 0 7",
    "turn": "b",
    "solutionUci": "b4e7",
    "solutionSan": "Be7",
    "motif": "tactic",
    "theme": "Mundur Taktis Mengamankan Struktur",
    "description": "Gajah b4 diserang pion c3. Mundurkan Gajah ke e7 secara disiplin.",
    "hintPiece": "Gajah hitam di b4.",
    "hintExplanation": "Mundurkan Gajah ke e7.",
    "trickExplanation": "Tips Blokh: Mundur pada posisi aman mempertahankan nilai perwira tanpa menciptakan kelemahan baru.",
    "xp": 100
  },
  {
    "id": "p36",
    "category": "middlegame",
    "difficulty": "Mudah",
    "track": "quest",
    "fen": "r2q1rk1/1pp2ppp/p1np4/4p3/B3P1b1/3P1N2/PPP2PPP/R1BQ1RK1 w - - 0 10",
    "turn": "w",
    "solutionUci": "a4c6",
    "solutionSan": "Bxc6",
    "motif": "capture",
    "theme": "Merusak Struktur Pion Sayap Menteri",
    "description": "Tukar Gajah a4 dengan Kuda c6 untuk menciptakan pion tumpuk (doubled pawns) pada posisi Hitam.",
    "hintPiece": "Gajah putih di a4.",
    "hintExplanation": "Pukul Kuda c6 dengan Gajah a4.",
    "trickExplanation": "Tips Blokh (Structural Damage): Merusak rantai pion lawan menciptakan target serangan jangka panjang.",
    "xp": 50
  }
];

export const PUZZLES: Puzzle[] = [
  {
    "id": "p01",
    "category": "opening",
    "difficulty": "Mudah",
    "track": "quest",
    "fen": "r1bqkb1r/pppp1ppp/2n5/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 0 4",
    "turn": "w",
    "solutionUci": "h5f7",
    "solutionSan": "Qxf7#",
    "motif": "mate",
    "theme": "Skakmat Scholar (Scholar's Mate)",
    "description": "Manfaatkan titik lemah f7 yang hanya dijaga oleh Raja Hitam di awal pembukaan.",
    "hintPiece": "Menteri putih di h5.",
    "hintExplanation": "Menteri memukul bidak di f7 dengan perlindungan Gajah c4 untuk skakmat langsung.",
    "trickExplanation": "Tips Blokh: Titik f7/f2 sebelum rokade adalah titik terlemah di papan karena hanya dilindungi Raja.",
    "xp": 50
  },
  {
    "id": "p02",
    "category": "opening",
    "difficulty": "Mudah",
    "track": "quest",
    "fen": "rnbqkbnr/ppppp1pp/5p2/8/4P3/6P1/PPPP1P1P/RNBQKBNR w KQkq - 0 2",
    "turn": "w",
    "solutionUci": "d1h5",
    "solutionSan": "Qh5+",
    "motif": "check",
    "theme": "Celah Diagonal Maut (Fool's Pattern)",
    "description": "Hitam melangkahkan f6 di langkah pembuka. Manfaatkan celah diagonal e8-h5.",
    "hintPiece": "Menteri putih di d1.",
    "hintExplanation": "Luncurkan Menteri ke h5 untuk memberikan skak keras pada raja Hitam.",
    "trickExplanation": "Tips Blokh: Memajukan pion-f terlalu dini merusak benteng pertahanan diagonal Raja secara permanen.",
    "xp": 50
  },
  {
    "id": "p03",
    "category": "opening",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "r1bqkb1r/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 2 4",
    "turn": "w",
    "solutionUci": "f3g5",
    "solutionSan": "Ng5",
    "motif": "tactic",
    "theme": "Giuoco Piano: Taktik Italia Serangan Titik Lemah f7",
    "description": "Dalam Pembukaan Italia (Giuoco Piano C50-C54), titik f7 adalah titik terlemah Hitam sebelum rokade. Luncurkan Kuda f3 ke g5 berkolaborasi dengan Gajah c4 untuk melancarkan serangan ganda ke f7!",
    "hintPiece": "Kuda putih di f3.",
    "hintExplanation": "Langkahkan Kuda f3 ke g5 untuk menambah ancaman ganda ke petak f7.",
    "trickExplanation": "Taktik Italia (Giuoco Piano): Koordinasi Gajah c4 + Kuda g5 mengeksploitasi titik terlemah f7 sebelum Raja Hitam sempat mengamankan diri lewat rokade.",
    "xp": 100
  },
  {
    "id": "p04",
    "category": "opening",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 4",
    "turn": "b",
    "solutionUci": "f6e4",
    "solutionSan": "Nxe4",
    "motif": "capture",
    "theme": "Garpu Pusat Kuda (Center Fork Trick)",
    "description": "Hitam memukul pion e4 untuk merebut inisiatif pusat lewat garpuan d7-d5 pada langkah berikutnya.",
    "hintPiece": "Kuda hitam di f6.",
    "hintExplanation": "Pukul pion e4 dengan Kuda hitam.",
    "trickExplanation": "Tips Blokh: Jika Putih membalas Nxe4, Hitam melangkah d7-d5 menggarpu Gajah dan Kuda putih.",
    "xp": 100
  },
  {
    "id": "p05",
    "category": "opening",
    "difficulty": "Sulit",
    "track": "quest",
    "fen": "r2qkb1r/pp1n1ppp/2p5/4N3/2B1P3/8/PPPP1PPP/RNBbK2R w KQkq - 0 8",
    "turn": "w",
    "solutionUci": "c4f7",
    "solutionSan": "Bxf7+",
    "motif": "capture-check",
    "theme": "Jebakan Legal (Legal's Trap Finale)",
    "description": "Hitam tergiur memakan Menteri Putih di d1. Hukum kecerobohan lawan dengan skak pengorbanan gajah!",
    "hintPiece": "Gajah putih di c4.",
    "hintExplanation": "Pukul bidak f7 dengan Gajah untuk skak dan memaksa Raja Hitam melangkah ke e7.",
    "trickExplanation": "Tips Blokh (Decoy & Attraction): Korbankan perwira berharga untuk menarik Raja lawan ke jaring skakmat.",
    "xp": 175
  },
  {
    "id": "p06",
    "category": "opening",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "r1bqkb1r/pp1npppp/2p2n2/8/3PN3/8/PPP1QPPP/R1B1KBNR w KQkq - 1 6",
    "turn": "w",
    "solutionUci": "e4d6",
    "solutionSan": "Nd6#",
    "motif": "mate",
    "theme": "Skakmat Tercekik Caro-Kann",
    "description": "Hitam memblokir petak pelarian raja. Manfaatkan pin mutlak Menteri e2 terhadap pion e7!",
    "hintPiece": "Kuda putih di e4.",
    "hintExplanation": "Lompatkan Kuda ke d6 untuk skakmat mutlak karena pion e7 ter-pin oleh Menteri e2.",
    "trickExplanation": "Tips Blokh (Pinning Exploitation): Bidak yang ter-pin tidak mampu menjalankan fungsinya menjaga petak.",
    "xp": 100
  },
  {
    "id": "p07",
    "category": "opening",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "r1b1k2r/ppppqppp/2n5/4n3/1PP5/5N2/1P1NPPPP/R2QKB1R b KQkq - 0 8",
    "turn": "b",
    "solutionUci": "e5d3",
    "solutionSan": "Nd3#",
    "motif": "mate",
    "theme": "Skakmat Budapest Gambit",
    "description": "Putih lengah memakan perwira di b4. Luncurkan Kuda hitam untuk menyelesaikan duel seketika!",
    "hintPiece": "Kuda hitam di e5.",
    "hintExplanation": "Lompatkan Kuda ke d3 untuk skakmat karena pion e2 ter-pin oleh Menteri e7.",
    "trickExplanation": "Tips Blokh: Manfaatkan lajur semi-terbuka untuk memaku bidak penjaga raja.",
    "xp": 100
  },
  {
    "id": "p08",
    "category": "opening",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "r1bqkb1r/pppn1ppp/5n2/3N2B1/3P4/8/PP2PPPP/R2QKBNR b KQkq - 0 6",
    "turn": "b",
    "solutionUci": "f6d5",
    "solutionSan": "Nxd5",
    "motif": "capture",
    "theme": "Jebakan Gajah Queen's Gambit (Elephant Trap)",
    "description": "Putih baru saja memukul d5 dengan Kuda. Balas dengan memukul kuda tersebut!",
    "hintPiece": "Kuda hitam di f6.",
    "hintExplanation": "Pukul Kuda d5 dengan Kuda f6. Jika Putih memakan menteri d8, Hitam membalas Bb4+!",
    "trickExplanation": "Tips Blokh: Umpan semu (Pseudo-sacrifice) yang memicu skakmat atau perolehan perwira kembali.",
    "xp": 100
  },
  {
    "id": "p09",
    "category": "opening",
    "difficulty": "Mudah",
    "track": "quest",
    "fen": "rnbqkbnr/pppp1ppp/8/4p3/4PP2/8/PPPP2PP/RNBQKBNR b KQkq - 0 2",
    "turn": "b",
    "solutionUci": "d8h4",
    "solutionSan": "Qh4+",
    "motif": "check",
    "theme": "Skak Serangan Balik King's Gambit",
    "description": "Putih membuka jalur sayap raja f2-f4 secara terburu-buru. Balas dengan serangan cepat!",
    "hintPiece": "Menteri hitam di d8.",
    "hintExplanation": "Langkahkan Menteri ke h4 untuk memberikan skak keras pada raja putih.",
    "trickExplanation": "Tips Blokh: Jangan membuka jalur sayap raja tanpa kalkulasi perlindungan raja yang matang.",
    "xp": 50
  },
  {
    "id": "p10",
    "category": "opening",
    "difficulty": "Sulit",
    "track": "quest",
    "fen": "r1b1kbnr/pppp1ppp/8/4n3/3PP2q/8/PPP2PPP/RNBQKBNR w KQkq - 1 5",
    "turn": "w",
    "solutionUci": "d4e5",
    "solutionSan": "dxe5",
    "motif": "capture",
    "theme": "Menghukum Manuver Menteri Terlalu Dini",
    "description": "Hitam melancarkan serangan menteri prematur dan meninggalkan Kuda di e5 tanpa perlindungan.",
    "hintPiece": "Pion putih di d4.",
    "hintExplanation": "Pukul Kuda hitam di e5 secara gratis dengan pion d4.",
    "trickExplanation": "Tips Blokh: Mengabaikan perkembangan perwira demi serangan menteri solo berujung kehilangan material.",
    "xp": 175
  },
  {
    "id": "p11",
    "category": "opening",
    "difficulty": "Mudah",
    "track": "quest",
    "fen": "r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 4 5",
    "turn": "w",
    "solutionUci": "e1g1",
    "solutionSan": "O-O",
    "motif": "tactic",
    "theme": "Rokade Dini Mengamankan Raja",
    "description": "Selesaikan tahap pembukaan dengan mengamankan Raja di sudut dan mengaktifkan Benteng.",
    "hintPiece": "Raja putih di e1.",
    "hintExplanation": "Lakukan rokade sayap raja (O-O) untuk menuntaskan koordinasi pertahanan.",
    "trickExplanation": "Tips Blokh: King safety adalah syarat utama sebelum melancarkan operasi taktis agresif.",
    "xp": 50
  },
  {
    "id": "p12",
    "category": "opening",
    "difficulty": "Sulit",
    "track": "quest",
    "fen": "r1bqk2r/pppp1ppp/2n5/1B2p3/4n3/5N2/PPPP1PPP/RNBQR1K1 w kq - 0 6",
    "turn": "w",
    "solutionUci": "e1e4",
    "solutionSan": "Rxe4",
    "motif": "capture",
    "theme": "Eksploitasi Pin Terbuka Ruy Lopez",
    "description": "Kuda Hitam di e4 berada pada jalur terbuka raja e8. Ambil keunggulan material!",
    "hintPiece": "Benteng putih di e1.",
    "hintExplanation": "Pukul Kuda di e4 dengan Benteng e1.",
    "trickExplanation": "Tips Blokh: Benteng di lajur terbuka vertikal langsung mengeksploitasi perwira di depan raja.",
    "xp": 175
  },
  {
    "id": "p13",
    "category": "defense",
    "difficulty": "Mudah",
    "track": "puzzle",
    "fen": "r1bqkb1r/pppn1ppp/4pn2/3p4/2PP4/2N2N2/PP2PPPP/R1BQKB1R w KQkq - 2 5",
    "turn": "w",
    "solutionUci": "c4d5",
    "solutionSan": "cxd5",
    "motif": "capture",
    "theme": "Meredakan Ketegangan Pion Pusat",
    "description": "Hitam menekan pusat d5. Selesaikan ketegangan untuk mengendalikan lajur semi-terbuka c.",
    "hintPiece": "Pion putih di c4.",
    "hintExplanation": "Pukul pion d5 dengan pion c4.",
    "trickExplanation": "Tips Blokh: Tukar pion di pusat untuk membuka lajur bagi manuver benteng.",
    "xp": 50
  },
  {
    "id": "p14",
    "category": "defense",
    "difficulty": "Sedang",
    "track": "puzzle",
    "fen": "r1bqk2r/ppp2ppp/2np1n2/2b1p3/2B1P3/2PP1N2/PP3PPP/RNBQ1RK1 b kq - 0 6",
    "turn": "b",
    "solutionUci": "c8g4",
    "solutionSan": "Bg4",
    "motif": "tactic",
    "theme": "Pin Pengunci Perwira Lawan",
    "description": "Kembangkan Gajah hitam ke g4 untuk memaku Kuda putih f3 terhadap Menteri d1.",
    "hintPiece": "Gajah hitam di c8.",
    "hintExplanation": "Langkahkan Gajah ke g4 untuk menetralisir agresi perwira putih.",
    "trickExplanation": "Tips Blokh (Pinning Counter): Memaku Kuda lawan melemahkan kontrolnya atas petak d4 dan e5.",
    "xp": 100
  },
  {
    "id": "p15",
    "category": "defense",
    "difficulty": "Sedang",
    "track": "puzzle",
    "fen": "r2qk2r/ppp2ppp/2n1bn2/3pp3/1b2P3/2PP1N2/PP1NBPPP/R1BQK2R w KQkq - 1 7",
    "turn": "w",
    "solutionUci": "c3b4",
    "solutionSan": "cxb4",
    "motif": "capture",
    "theme": "Menghalau Gajah Agresif",
    "description": "Hitam melangkah terlalu maju dengan Bb4. Ambil keuntungan perwira gratis!",
    "hintPiece": "Pion putih di c3.",
    "hintExplanation": "Pukul Gajah b4 dengan pion c3.",
    "trickExplanation": "Tips Blokh: Selalu verifikasi apakah serangan lawan memiliki pelindung yang sah sebelum bertahan pasif.",
    "xp": 100
  },
  {
    "id": "p16",
    "category": "defense",
    "difficulty": "Sulit",
    "track": "puzzle",
    "fen": "r1b1k2r/ppppqppp/2n5/4P3/1bB1n3/2N2N2/PPP2PPP/R1BQK2R w KQkq - 1 7",
    "turn": "w",
    "solutionUci": "e1g1",
    "solutionSan": "O-O",
    "motif": "tactic",
    "theme": "Lepaskan Pin Lewat Rokade",
    "description": "Kuda c3 terancam ganda karena ter-pin. Lepaskan pin mutlak dengan mengamankan raja!",
    "hintPiece": "Raja putih di e1.",
    "hintExplanation": "Lakukan rokade (O-O) untuk menghilangkan pin terhadap Raja putih.",
    "trickExplanation": "Tips Blokh: Rokade seringkali merupakan cara tercepat mematahkan pin mutlak lawan.",
    "xp": 175
  },
  {
    "id": "p17",
    "category": "defense",
    "difficulty": "Mudah",
    "track": "puzzle",
    "fen": "r1bqkb1r/pppp1ppp/2n5/4P3/4n3/5N2/PPP1PPPP/RNBQKB1R w KQkq - 1 5",
    "turn": "w",
    "solutionUci": "d1d5",
    "solutionSan": "Qd5",
    "motif": "tactic",
    "theme": "Garpu Menteri Serangan Balik",
    "description": "Kuda Hitam di e4 tidak terjaga. Gunakan Menteri d1 untuk menyerang Kuda sekaligus mengancam petak f7!",
    "hintPiece": "Menteri putih di d1.",
    "hintExplanation": "Langkahkan Menteri ke d5 untuk menyerang Kuda e4 dan pion f7.",
    "trickExplanation": "Tips Blokh (Double Attack): Menteri yang terpusat mampu menciptakan dua ancaman mematikan sekaligus.",
    "xp": 50
  },
  {
    "id": "p18",
    "category": "defense",
    "difficulty": "Sulit",
    "track": "puzzle",
    "fen": "r2q1rk1/1pp2ppp/p1np1n2/2b1p1B1/2B1P1b1/2NP1N2/PPP2PPP/R2Q1RK1 w - - 2 9",
    "turn": "w",
    "solutionUci": "c3d5",
    "solutionSan": "Nd5",
    "motif": "tactic",
    "theme": "Menumpuk Tekanan Pada Perwira Terpaku",
    "description": "Kuda Hitam di f6 ter-pin oleh Gajah g5. Tambah daya serang dengan meluncurkan Kuda c3!",
    "hintPiece": "Kuda putih di c3.",
    "hintExplanation": "Langkahkan Kuda ke d5 untuk menekan titik kritis f6.",
    "trickExplanation": "Tips Blokh (Pile On Pinned Piece): Tingkatkan penyerang pada perwira yang terpaku sampai pertahanan lawan jebol.",
    "xp": 175
  },
  {
    "id": "p19",
    "category": "middlegame",
    "difficulty": "Mudah",
    "track": "puzzle",
    "fen": "r1b2rk1/pp3ppp/2n5/3qp3/8/3B1N2/PPP2PPP/R2Q1RK1 w - - 0 12",
    "turn": "w",
    "solutionUci": "d3h7",
    "solutionSan": "Bxh7+",
    "motif": "capture-check",
    "theme": "Greek Gift & Skak Terselubung (Discovered Attack)",
    "description": "Menteri Hitam di d5 tidak terjaga. Buka serangan terselubung dengan memukul bidak h7!",
    "hintPiece": "Gajah putih di d3.",
    "hintExplanation": "Pukul bidak h7 dengan Gajah untuk skak dan memenangkan Menteri Hitam d5 di langkah berikutnya.",
    "trickExplanation": "Tips Blokh (Discovered Attack): Serangan terbuka dengan tempo skak melumpuhkan perwira lawan tanpa ampun.",
    "xp": 50
  },
  {
    "id": "p20",
    "category": "middlegame",
    "difficulty": "Sedang",
    "track": "puzzle",
    "fen": "r4rk1/1pp2ppp/p7/3q4/3n4/5N2/PP3PPP/R2QR1K1 w - - 0 16",
    "turn": "w",
    "solutionUci": "d1d4",
    "solutionSan": "Qxd4",
    "motif": "capture",
    "theme": "Penghancuran Penjaga (Annihilation of Defence)",
    "description": "Kuda d4 tidak memiliki pelindung yang cukup. Ambil perwira tersebut!",
    "hintPiece": "Menteri putih di d1.",
    "hintExplanation": "Pukul Kuda d4 dengan Menteri Putih.",
    "trickExplanation": "Tips Blokh: Identifikasi perwira bebas tanpa pengawalan (undefended piece) dan rebut inisiatif.",
    "xp": 100
  },
  {
    "id": "p21",
    "category": "middlegame",
    "difficulty": "Sulit",
    "track": "puzzle",
    "fen": "r3r1k1/ppp2ppp/2n5/3q4/3P4/5N2/PP1Q1PPP/R3R1K1 b - - 2 15",
    "turn": "b",
    "solutionUci": "e8e1",
    "solutionSan": "Rxe1+",
    "motif": "capture-check",
    "theme": "Dominasi Lajur Vertikal Terbuka (File Clearance)",
    "description": "Tukar Benteng di e1 untuk menguasai jalur e dengan Benteng a8.",
    "hintPiece": "Benteng hitam di e8.",
    "hintExplanation": "Pukul Benteng putih di e1.",
    "trickExplanation": "Tips Blokh (Line Clearance): Mengeliminasi penjaga lajur terbuka memberikan keunggulan positioning strategis.",
    "xp": 175
  },
  {
    "id": "p22",
    "category": "middlegame",
    "difficulty": "Mudah",
    "track": "puzzle",
    "fen": "r1bqk2r/ppp2ppp/2n5/3np3/1b6/2NP1N2/PPP1BPPP/R1BQK2R w KQkq - 2 7",
    "turn": "w",
    "solutionUci": "c1d2",
    "solutionSan": "Bd2",
    "motif": "tactic",
    "theme": "Menutup Skak Sambil Menetralisir Pin",
    "description": "Gajah b4 memaku Kuda c3. Kembangkan Gajah d2 untuk mengamankan posisi.",
    "hintPiece": "Gajah putih di c1.",
    "hintExplanation": "Langkahkan Gajah ke d2.",
    "trickExplanation": "Tips Blokh: Netralisir pin sebelum melancarkan langkah operasional berikutnya.",
    "xp": 50
  },
  {
    "id": "p23",
    "category": "middlegame",
    "difficulty": "Sedang",
    "track": "puzzle",
    "fen": "r2q1rk1/1pp2ppp/p1np4/4p3/B3P1b1/3P1N2/PPP2PPP/R2Q1RK1 b - - 0 11",
    "turn": "b",
    "solutionUci": "c6d4",
    "solutionSan": "Nd4",
    "motif": "tactic",
    "theme": "Penumpukan Tekanan Pada Sayap Raja",
    "description": "Tingkatkan serangan ke Kuda f3 yang ter-pin dengan menempatkan Kuda ke d4.",
    "hintPiece": "Kuda hitam di c6.",
    "hintExplanation": "Lompatkan Kuda ke d4.",
    "trickExplanation": "Tips Blokh: Serang titik tumpu lawan yang lumpuh oleh pin.",
    "xp": 100
  },
  {
    "id": "p24",
    "category": "middlegame",
    "difficulty": "Sulit",
    "track": "puzzle",
    "fen": "r4rk1/ppp2ppp/8/3q4/8/5N2/PP3PPP/R2QR1K1 w - - 0 17",
    "turn": "w",
    "solutionUci": "d1d5",
    "solutionSan": "Qxd5",
    "motif": "capture",
    "theme": "Penyederhanaan Menuju Babak Akhir Unggul",
    "description": "Menteri Hitam d5 tidak terjaga. Menangkan Menteri lawan secara cuma-cuma!",
    "hintPiece": "Menteri putih di d1.",
    "hintExplanation": "Pukul Menteri Hitam di d5.",
    "trickExplanation": "Tips Blokh: Ketika unggul atau mendapati blunder lawan, lakukan simplifikasi konkrit.",
    "xp": 175
  },
  {
    "id": "p25",
    "category": "endgame",
    "difficulty": "Mudah",
    "track": "quest",
    "fen": "8/5k2/8/8/8/8/4P3/4K3 w - - 0 1",
    "turn": "w",
    "solutionUci": "e1d2",
    "solutionSan": "Kd2",
    "motif": "tactic",
    "theme": "Oposisi Raja Membimbing Pion",
    "description": "Aktifkan Raja untuk mengawal pion maju menuju petak promosi.",
    "hintPiece": "Raja putih di e1.",
    "hintExplanation": "Langkahkan Raja ke d2.",
    "trickExplanation": "Tips Blokh (King Opposition): Di babak akhir, Raja adalah perwira penyerang utama pembuka jalan pion.",
    "xp": 50
  },
  {
    "id": "p26",
    "category": "endgame",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "8/8/8/8/4k3/4p3/4K3/8 w - - 0 1",
    "turn": "w",
    "solutionUci": "e2e1",
    "solutionSan": "Ke1",
    "motif": "tactic",
    "theme": "Pertahanan Oposisi Menahan Pion Lawan",
    "description": "Pion Hitam di e3. Mundurkan Raja putih ke petak e1 tepat di depan pion lawan untuk menahan remis.",
    "hintPiece": "Raja putih di e2.",
    "hintExplanation": "Mundurkan Raja ke e1.",
    "trickExplanation": "Tips Blokh (Endgame Opposition): Mundur lurus di depan pion lawan untuk merebut oposisi saat Raja lawan maju.",
    "xp": 100
  },
  {
    "id": "p27",
    "category": "endgame",
    "difficulty": "Sulit",
    "track": "quest",
    "fen": "8/4P3/8/8/8/5k2/8/4K3 w - - 0 1",
    "turn": "w",
    "solutionUci": "e7e8q",
    "solutionSan": "e8=Q",
    "motif": "promotion",
    "theme": "Promosi Menteri Penentu Kemenangan",
    "description": "Pion Putih di e7 siap promosi menjadi Menteri baru!",
    "hintPiece": "Pion putih di e7.",
    "hintExplanation": "Dorong pion ke e8 dan promosikan menjadi Menteri (Q).",
    "trickExplanation": "Tips Blokh (Pawn Breakthrough): Perhitungan langkah pion menuju baris ke-8 adalah fondasi kemenangan endgame.",
    "xp": 175
  },
  {
    "id": "p28",
    "category": "endgame",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "4k3/R7/8/8/8/8/8/4K3 w - - 0 1",
    "turn": "w",
    "solutionUci": "a7h7",
    "solutionSan": "Rh7",
    "motif": "tactic",
    "theme": "Memotong Jalur Raja Lawan (Rook Cut)",
    "description": "Kunci Raja hitam di baris ke-8 dengan menggeser Benteng di baris ke-7.",
    "hintPiece": "Benteng putih di a7.",
    "hintExplanation": "Geser Benteng ke h7.",
    "trickExplanation": "Tips Blokh (7th Rank Domination): Benteng di baris ke-7 mengurung Raja lawan dan memutus mobilitasnya.",
    "xp": 100
  },
  {
    "id": "p29",
    "category": "endgame",
    "difficulty": "Mudah",
    "track": "quest",
    "fen": "8/8/8/8/8/4k3/R7/4K3 w - - 0 1",
    "turn": "w",
    "solutionUci": "a2a3",
    "solutionSan": "Ra3+",
    "motif": "check",
    "theme": "Skak Pemutus Oposisi",
    "description": "Gunakan Benteng untuk memberi skak horizontal dan memaksa Raja lawan mundur.",
    "hintPiece": "Benteng putih di a2.",
    "hintExplanation": "Langkahkan Benteng ke a3 untuk memberi skak.",
    "trickExplanation": "Tips Blokh: Skak horizontal memisahkan Raja musuh dari perlindungan pion.",
    "xp": 50
  },
  {
    "id": "p30",
    "category": "endgame",
    "difficulty": "Sulit",
    "track": "quest",
    "fen": "8/8/8/8/8/5k2/7p/5K2 b - - 0 1",
    "turn": "b",
    "solutionUci": "h2h1q",
    "solutionSan": "h1=Q#",
    "motif": "mate",
    "theme": "Skakmat Promosi Sudut",
    "description": "Pion h2 melangkah ke h1 dan promosi menjadi Menteri untuk skakmat seketika!",
    "hintPiece": "Pion hitam di h2.",
    "hintExplanation": "Dorong pion ke h1 dan jadikan Menteri (Q#).",
    "trickExplanation": "Tips Blokh: Promosi dengan tempo skakmat menyudahi duel seketika tanpa perlawanan.",
    "xp": 175
  },
  {
    "id": "p31",
    "category": "middlegame",
    "difficulty": "Sulit",
    "track": "quest",
    "fen": "3r2k1/p4ppp/1p6/8/8/8/PP3PPP/3RR1K1 w - - 0 1",
    "turn": "w",
    "solutionUci": "d1d8",
    "solutionSan": "Rxd8#",
    "motif": "mate",
    "theme": "Skakmat Koridor Baris Belakang (Back-Rank Mate)",
    "description": "Benteng Hitam di d8 tidak memiliki perlindungan pendukung dan baris ke-8 terkunci oleh pionnya sendiri.",
    "hintPiece": "Benteng putih di d1.",
    "hintExplanation": "Pukul Benteng d8 dengan Benteng d1 untuk skakmat mutlak.",
    "trickExplanation": "Tips Blokh (Back-Rank Exploitation): Selalu waspadai ketiadaan petak pelarian (luft) pada baris belakang lawan.",
    "xp": 175
  },
  {
    "id": "p32",
    "category": "middlegame",
    "difficulty": "Sulit",
    "track": "quest",
    "fen": "r1b2rk1/pp3ppp/2n1p3/2qpP3/8/3B1N2/PPP2PPP/R2Q1RK1 w - - 0 12",
    "turn": "w",
    "solutionUci": "d3h7",
    "solutionSan": "Bxh7+",
    "motif": "capture-check",
    "theme": "Pengorbanan Klasik Greek Gift (Bxh7+)",
    "description": "Hancurkan perisai pion h7 raja Hitam untuk membuka jaring serangan Kuda Ng5+ dan Menteri Qh5!",
    "hintPiece": "Gajah putih di d3.",
    "hintExplanation": "Pukul pion h7 dengan Gajah untuk skak dan membongkar tempat persembunyian raja.",
    "trickExplanation": "Tips Blokh (Demolition of King Cover): Pengorbanan Gajah di h7 adalah senjata taktis utama menghadapi rokade pendek.",
    "xp": 175
  },
  {
    "id": "p33",
    "category": "middlegame",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "r4rk1/pp1b1ppp/1qn1p3/3p4/8/1P1B1N2/P1P2PPP/R2QR1K1 w - - 0 14",
    "turn": "w",
    "solutionUci": "d3h7",
    "solutionSan": "Bxh7+",
    "motif": "capture-check",
    "theme": "Colle System: Serangan Greek Gift (Bxh7+)",
    "description": "Dalam Colle System (D05), formasi piramida d4-e3 dan dorongan e4 membuka diagonal Gajah d3 lurus ke sayap raja Hitam. Korbankan Gajah di h7 untuk membongkar pertahanan rokade lawan!",
    "hintPiece": "Gajah putih di d3.",
    "hintExplanation": "Pukul pion h7 dengan Gajah putih untuk membuka posisi Raja lawan.",
    "trickExplanation": "Taktik Colle System: Pengorbanan Gajah h7 (Greek Gift) adalah trik utama Colle saat Kuda lawan tak lagi mengawal petak f6.",
    "xp": 100
  },
  {
    "id": "p34",
    "category": "middlegame",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "r1b1k2r/ppppqppp/2n5/4n3/1bP5/5N2/PP1NPPPP/R1BQKB1R w KQkq - 0 7",
    "turn": "w",
    "solutionUci": "a2a3",
    "solutionSan": "a3",
    "motif": "tactic",
    "theme": "Pengusiran Gajah Pengganggu",
    "description": "Gajah b4 menekan perwira putih. Usir segera dengan dorongan pion a3!",
    "hintPiece": "Pion putih di a2.",
    "hintExplanation": "Langkahkan pion ke a3 untuk mengancam Gajah b4.",
    "trickExplanation": "Tips Blokh: Kembalikan inisiatif dengan menyerang perwira depan lawan.",
    "xp": 100
  },
  {
    "id": "p35",
    "category": "defense",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "r1bqk2r/ppp2ppp/2n5/3np3/1b6/2PP1N2/PP1BBPPP/RN1QK2R b KQkq - 0 7",
    "turn": "b",
    "solutionUci": "b4e7",
    "solutionSan": "Be7",
    "motif": "tactic",
    "theme": "Mundur Taktis Mengamankan Struktur",
    "description": "Gajah b4 diserang pion c3. Mundurkan Gajah ke e7 secara disiplin.",
    "hintPiece": "Gajah hitam di b4.",
    "hintExplanation": "Mundurkan Gajah ke e7.",
    "trickExplanation": "Tips Blokh: Mundur pada posisi aman mempertahankan nilai perwira tanpa menciptakan kelemahan baru.",
    "xp": 100
  },
  {
    "id": "p36",
    "category": "middlegame",
    "difficulty": "Mudah",
    "track": "quest",
    "fen": "r2q1rk1/1pp2ppp/p1np4/4p3/B3P1b1/3P1N2/PPP2PPP/R1BQ1RK1 w - - 0 10",
    "turn": "w",
    "solutionUci": "a4c6",
    "solutionSan": "Bxc6",
    "motif": "capture",
    "theme": "Merusak Struktur Pion Sayap Menteri",
    "description": "Tukar Gajah a4 dengan Kuda c6 untuk menciptakan pion tumpuk (doubled pawns) pada posisi Hitam.",
    "hintPiece": "Gajah putih di a4.",
    "hintExplanation": "Pukul Kuda c6 dengan Gajah a4.",
    "trickExplanation": "Tips Blokh (Structural Damage): Merusak rantai pion lawan menciptakan target serangan jangka panjang.",
    "xp": 50
  },
  {
    "id": "p37",
    "category": "defense",
    "difficulty": "Mudah",
    "track": "puzzle",
    "fen": "r1b2rk1/pp3ppp/2n5/3qp3/8/3B1N2/PPP2PPP/R1BQ1RK1 b - - 1 11",
    "turn": "b",
    "solutionUci": "e5e4",
    "solutionSan": "e4",
    "motif": "tactic",
    "theme": "Garpu Pion Tengah (Pawn Fork)",
    "description": "Gajah d3 dan Kuda f3 Putih berada pada satu garis garpuan. Majukan pion e5!",
    "hintPiece": "Pion hitam di e5.",
    "hintExplanation": "Dorong pion ke e4 untuk menggarpu Gajah d3 dan Kuda f3 sekaligus.",
    "trickExplanation": "Tips Blokh (Pawn Fork): Garpu pion adalah taktik sederhana berdaya hancur tinggi untuk merebut perwira ringan.",
    "xp": 50
  },
  {
    "id": "p38",
    "category": "middlegame",
    "difficulty": "Sedang",
    "track": "puzzle",
    "fen": "r1bq1rk1/ppp2ppp/2np4/2b1p1B1/2B1P1n1/2NP1N2/PPP2PPP/R2Q1RK1 b - - 3 8",
    "turn": "b",
    "solutionUci": "d8e8",
    "solutionSan": "Qe8",
    "motif": "tactic",
    "theme": "Menghindar dari Serangan Menteri Terselubung",
    "description": "Menteri Hitam diserang Gajah g5. Pindahkan Menteri ke e8 untuk menjaga koordinasi.",
    "hintPiece": "Menteri hitam di d8.",
    "hintExplanation": "Pindahkan Menteri ke e8.",
    "trickExplanation": "Tips Blokh: Amankan perwira terberat sebelum lawan memanfaatkan tempo serangan.",
    "xp": 100
  },
  {
    "id": "p39",
    "category": "middlegame",
    "difficulty": "Sulit",
    "track": "puzzle",
    "fen": "r4rk1/1pp2ppp/p7/3q4/3n4/5N2/PP1Q1PPP/R3R1K1 b - - 1 16",
    "turn": "b",
    "solutionUci": "d4f3",
    "solutionSan": "Nxf3+",
    "motif": "capture-check",
    "theme": "Penghancuran Pertahanan Sayap Raja (Decisive Exchange)",
    "description": "Pukul Kuda f3 dengan skak untuk membongkar rantai pion g2 di depan Raja putih.",
    "hintPiece": "Kuda hitam di d4.",
    "hintExplanation": "Pukul Kuda f3 dengan skak.",
    "trickExplanation": "Tips Blokh (Annihilation of Defence): Menghilangkan perwira bertahan memaksa pion merusak benteng rajanya sendiri.",
    "xp": 175
  },
  {
    "id": "p40",
    "category": "endgame",
    "difficulty": "Mudah",
    "track": "puzzle",
    "fen": "8/8/4k3/8/8/4K3/4P3/8 w - - 0 1",
    "turn": "w",
    "solutionUci": "e3e4",
    "solutionSan": "Ke4",
    "motif": "tactic",
    "theme": "Mengambil Oposisi Vertikal",
    "description": "Maju dengan Raja ke e4 tepat berhadapan dengan Raja lawan (oposisi langsung).",
    "hintPiece": "Raja putih di e3.",
    "hintExplanation": "Langkahkan Raja ke e4.",
    "trickExplanation": "Tips Blokh: Mengambil oposisi memaksa Raja bertahan mundur atau memberi jalan bagi pion.",
    "xp": 50
  },
  {
    "id": "p41",
    "category": "opening",
    "difficulty": "Mudah",
    "track": "puzzle",
    "fen": "r1bqkb1r/pppp1ppp/2n5/4p3/3Pn3/2P2N2/PP3PPP/RNBQKB1R w KQkq - 0 5",
    "turn": "w",
    "solutionUci": "f1d3",
    "solutionSan": "Bd3",
    "motif": "tactic",
    "theme": "Pengembangan Perwira Sambil Mengancam",
    "description": "Kembangkan Gajah ke d3 untuk menekan Kuda hitam di e4.",
    "hintPiece": "Gajah putih di f1.",
    "hintExplanation": "Langkahkan Gajah ke d3.",
    "trickExplanation": "Tips Blokh: Menggabungkan tempo perkembangan perwira dengan ancaman langsung merebut kontrol inisiatif.",
    "xp": 50
  },
  {
    "id": "p42",
    "category": "middlegame",
    "difficulty": "Sedang",
    "track": "puzzle",
    "fen": "r2q1rk1/ppp2ppp/2n5/3p4/1b1Pn3/2NBPN2/PPP2PPP/R1BQK2R b KQ - 2 9",
    "turn": "b",
    "solutionUci": "e4c3",
    "solutionSan": "Nxc3",
    "motif": "capture",
    "theme": "Menghancurkan Kuda Penjaga Pusat",
    "description": "Pukul Kuda c3 dengan Kuda e4 untuk merusak integritas pion lawan.",
    "hintPiece": "Kuda hitam di e4.",
    "hintExplanation": "Pukul Kuda c3 dengan Kuda e4.",
    "trickExplanation": "Tips Blokh: Memecah koordinasi perwira lawan dengan pertukaran taktis yang menguntungkan struktur.",
    "xp": 100
  },
  {
    "id": "p43",
    "category": "middlegame",
    "difficulty": "Sulit",
    "track": "puzzle",
    "fen": "r1bq1rk1/pppn1ppp/4p3/3pP3/8/3BP3/PPPN1PPP/R2QK2R w KQ - 1 10",
    "turn": "w",
    "solutionUci": "d3h7",
    "solutionSan": "Bxh7+",
    "motif": "capture-check",
    "theme": "Greek Gift Finale",
    "description": "Luncurkan pengorbanan Gajah di h7 untuk mematahkan perlindungan sayap raja Hitam!",
    "hintPiece": "Gajah putih di d3.",
    "hintExplanation": "Pukul bidak h7 dengan Gajah untuk skak.",
    "trickExplanation": "Tips Blokh: Kombinasi Greek Gift efektif saat lawan belum menempatkan perwira penjaga di f6/f8.",
    "xp": 175
  },
  {
    "id": "p44",
    "category": "middlegame",
    "difficulty": "Sedang",
    "track": "puzzle",
    "fen": "r1bq1rk1/pp1n1p1p/4p1p1/3pP3/8/3BP3/PPPN1PPP/R2QK2R w KQ - 0 11",
    "turn": "w",
    "solutionUci": "d1g4",
    "solutionSan": "Qg4",
    "motif": "tactic",
    "theme": "Aktivasi Menteri Menuju Sayap Raja",
    "description": "Luncurkan Menteri ke g4 untuk menekan titik lemah g6 dan h7.",
    "hintPiece": "Menteri putih di d1.",
    "hintExplanation": "Langkahkan Menteri ke g4.",
    "trickExplanation": "Tips Blokh: Mobilisasi menteri ke sayap raja pasca-kerusakan pion menciptakan ancaman mate beruntun.",
    "xp": 100
  },
  {
    "id": "p45",
    "category": "defense",
    "difficulty": "Sedang",
    "track": "puzzle",
    "fen": "r1bq1rk1/pp3ppp/2n1pn2/2pp4/2PP4/2N1PN2/PP3PPP/R1BQKB1R w KQ - 0 8",
    "turn": "w",
    "solutionUci": "c4d5",
    "solutionSan": "cxd5",
    "motif": "capture",
    "theme": "Pembersihan Jalur Pusat Semi-Terbuka",
    "description": "Pukul pion d5 dengan c4 untuk memperjelas formasi pusat.",
    "hintPiece": "Pion putih di c4.",
    "hintExplanation": "Pukul pion d5.",
    "trickExplanation": "Tips Blokh: Transisi pion pusat mengarahkan permainan ke variasi yang lebih terkendali.",
    "xp": 100
  },
  {
    "id": "p46",
    "category": "defense",
    "difficulty": "Sulit",
    "track": "puzzle",
    "fen": "r1bq1rk1/pp2bppp/2n1pn2/2pp4/3P4/2PBPN2/PP1N1PPP/R1BQK2R w KQ - 1 8",
    "turn": "w",
    "solutionUci": "e1g1",
    "solutionSan": "O-O",
    "motif": "tactic",
    "theme": "Rokade Mengamankan Transisi Babak Tengah",
    "description": "Amankan Raja Putih dengan rokade sebelum memulai operasi taktis di sayap menteri.",
    "hintPiece": "Raja putih di e1.",
    "hintExplanation": "Lakukan rokade (O-O).",
    "trickExplanation": "Tips Blokh: Keselamatan Raja adalah investasi awal sebelum memicu komplikasi taktis.",
    "xp": 175
  },
  {
    "id": "p47",
    "category": "endgame",
    "difficulty": "Mudah",
    "track": "puzzle",
    "fen": "8/8/8/3k4/3P4/3K4/8/8 w - - 0 1",
    "turn": "w",
    "solutionUci": "d3e3",
    "solutionSan": "Ke3",
    "motif": "tactic",
    "theme": "Melangkah ke Sisi Mengawal Pion Maju",
    "description": "Raja Hitam menahan oposisi d5. Geser Raja putih ke e3 untuk mendampingi dorongan pion.",
    "hintPiece": "Raja putih di d3.",
    "hintExplanation": "Langkahkan Raja ke e3.",
    "trickExplanation": "Tips Blokh: Mengitari Raja musuh saat memegang pion bebas mengamankan petak kunci promosi.",
    "xp": 50
  },
  {
    "id": "p48",
    "category": "endgame",
    "difficulty": "Sedang",
    "track": "puzzle",
    "fen": "8/8/4k3/3p4/3P4/4K3/8/8 b - - 0 1",
    "turn": "b",
    "solutionUci": "e6f5",
    "solutionSan": "Kf5",
    "motif": "tactic",
    "theme": "Infiltrasi Raja ke Sayap Lemah",
    "description": "Langkahkan Raja hitam ke f5 untuk menekan pion d4 dan menguasai ruang.",
    "hintPiece": "Raja hitam di e6.",
    "hintExplanation": "Langkahkan Raja ke f5.",
    "trickExplanation": "Tips Blokh: Aktivitas Raja di babak akhir adalah faktor penentu antara menang atau remis.",
    "xp": 100
  },
  {
    "id": "p49",
    "category": "endgame",
    "difficulty": "Sulit",
    "track": "puzzle",
    "fen": "8/8/8/8/8/5k2/4p3/4K3 w - - 0 1",
    "turn": "w",
    "solutionUci": "e1d2",
    "solutionSan": "Kd2",
    "motif": "tactic",
    "theme": "Menghindari Jebakan Remis Stalemate",
    "description": "Raja putih harus keluar ke d2 untuk membebaskan ruang dan memaksa langkah lanjutan.",
    "hintPiece": "Raja putih di e1.",
    "hintExplanation": "Langkahkan Raja ke d2.",
    "trickExplanation": "Tips Blokh: Perhitungan akurat petak Raja mencegah kebuntuan (stalemate) yang tidak disengaja.",
    "xp": 175
  },
  {
    "id": "p50",
    "category": "endgame",
    "difficulty": "Mudah",
    "track": "puzzle",
    "fen": "8/8/8/8/8/4k3/4p3/4K3 b - - 1 1",
    "turn": "b",
    "solutionUci": "e3d3",
    "solutionSan": "Kd3",
    "motif": "tactic",
    "theme": "Mempertahankan Tekanan Babak Akhir",
    "description": "Langkahkan Raja hitam ke d3 untuk terus mengawal pion e2.",
    "hintPiece": "Raja hitam di e3.",
    "hintExplanation": "Langkahkan Raja ke d3.",
    "trickExplanation": "Tips Blokh: Jaga jarak satu langkah dari pion promosi untuk melindungi titik singgasana menteri.",
    "xp": 50
  },
  {
    "id": "p51",
    "category": "middlegame",
    "difficulty": "Sedang",
    "track": "puzzle",
    "fen": "r2q1rk1/pb3ppp/1pn1pn2/2pp4/2PP4/2NBPN2/PP3PPP/R1BQK2R w KQ - 0 9",
    "turn": "w",
    "solutionUci": "e1g1",
    "solutionSan": "O-O",
    "motif": "tactic",
    "theme": "Persiapan Serangan Sayap Raja (Maxim Blokh CT-Art)",
    "description": "Amankan Raja Putih dengan rokade sebelum mengeksekusi manuver pembongkaran pion pusat.",
    "hintPiece": "Raja putih di e1.",
    "hintExplanation": "Lakukan rokade sayap raja (O-O).",
    "trickExplanation": "Tips Blokh (Prophylaxis): Pastikan raja aman di sudut sebelum melancarkan terobosan pion pusat.",
    "xp": 100
  },
  {
    "id": "p52",
    "category": "opening",
    "difficulty": "Mudah",
    "track": "puzzle",
    "fen": "r1bqk2r/pppp1ppp/2n2n2/4p3/1bB1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 4 5",
    "turn": "w",
    "solutionUci": "e1g1",
    "solutionSan": "O-O",
    "motif": "tactic",
    "theme": "Rokade Mengatasi Pin Gajah Empat Kuda",
    "description": "Gajah b4 memaku Kuda c3. Amankan Raja Putih dengan rokade.",
    "hintPiece": "Raja putih di e1.",
    "hintExplanation": "Lakukan rokade (O-O).",
    "trickExplanation": "Tips Blokh: Rokade dini menghilangkan potensi skak berbahaya di lajur e.",
    "xp": 50
  },
  {
    "id": "p53",
    "category": "defense",
    "difficulty": "Sedang",
    "track": "puzzle",
    "fen": "r1bqk2r/pppp1ppp/2n5/4p3/1b2n3/2NP1N2/PPP1BPPP/R1BQK2R w KQkq - 0 6",
    "turn": "w",
    "solutionUci": "d3e4",
    "solutionSan": "dxe4",
    "motif": "capture",
    "theme": "Menghukum Pengorbanan Palsu",
    "description": "Hitam melompat dengan Kuda e4 tanpa kalkulasi cukup. Pukul Kuda tersebut dengan pion d3!",
    "hintPiece": "Pion putih di d3.",
    "hintExplanation": "Pukul Kuda e4 dengan pion d3.",
    "trickExplanation": "Tips Blokh: Rebut keunggulan perwira saat lawan melancarkan kombinasi prematur.",
    "xp": 100
  },
  {
    "id": "p54",
    "category": "middlegame",
    "difficulty": "Sulit",
    "track": "puzzle",
    "fen": "r1b2rk1/pp1n1ppp/2p1pn2/3p4/2PP4/2N1PN2/PP3PPP/R1BQKB1R w KQ - 0 8",
    "turn": "w",
    "solutionUci": "f1d3",
    "solutionSan": "Bd3",
    "motif": "tactic",
    "theme": "Pengembangan Gajah Menuju Diagonal Maut b1-h7",
    "description": "Kembangkan Gajah ke d3 untuk mengarahkan moncong serangan langsung ke sayap raja Hitam.",
    "hintPiece": "Gajah putih di f1.",
    "hintExplanation": "Langkahkan Gajah ke d3.",
    "trickExplanation": "Tips Blokh (Diagonal Control): Mengarahkan Gajah ke petak h7 mempersiapkan fondasi kombinasi taktikal.",
    "xp": 175
  },
  {
    "id": "p55",
    "category": "endgame",
    "difficulty": "Sulit",
    "track": "puzzle",
    "fen": "8/8/8/8/3k4/8/3p4/3K4 w - - 0 1",
    "turn": "w",
    "solutionUci": "d1d2",
    "solutionSan": "Kxd2",
    "motif": "capture",
    "theme": "Menghabisi Pion Bebas Lawan (Eliminating Passed Pawn)",
    "description": "Pion Hitam di d2 tidak dapat dipertahankan. Pukul pion d2 dengan Raja Putih!",
    "hintPiece": "Raja putih di d1.",
    "hintExplanation": "Pukul pion d2 dengan Raja Putih.",
    "trickExplanation": "Tips Blokh: Ambil pion promosi lawan saat Raja lawan tidak memiliki tempo untuk melindunginya.",
    "xp": 175
  },
  {
    "id": "p56",
    "category": "middlegame",
    "difficulty": "Mudah",
    "track": "puzzle",
    "fen": "r2q1rk1/ppp2ppp/2n5/3p4/3Pn3/2NBPN2/PPP2PPP/R1BQK2R w KQ - 1 9",
    "turn": "w",
    "solutionUci": "d3e4",
    "solutionSan": "Bxe4",
    "motif": "capture",
    "theme": "Menghabisi Perwira Maju di Pusat (Annihilation of Defence)",
    "description": "Kuda Hitam di e4 menguasai petak sentral. Eliminasi Kuda tersebut dengan Gajah d3!",
    "hintPiece": "Gajah putih di d3.",
    "hintExplanation": "Pukul Kuda e4 dengan Gajah d3.",
    "trickExplanation": "Tips Blokh (Eliminating Outposts): Jangan biarkan perwira musuh bersarang di petak kunci sentralmu.",
    "xp": 50
  },
  {
    "id": "p57",
    "category": "opening",
    "difficulty": "Mudah",
    "track": "puzzle",
    "fen": "r1bqkb1r/pppp1ppp/2n2n2/4p3/4P3/2N2N2/PPPP1PPP/R1BQKB1R w KQkq - 2 4",
    "turn": "w",
    "solutionUci": "f1c4",
    "solutionSan": "Bc4",
    "motif": "tactic",
    "theme": "Pengembangan Perwira Empat Kuda (Four Knights Game)",
    "description": "Kembangkan Gajah ke c4 untuk menekan titik lemah f7.",
    "hintPiece": "Gajah putih di f1.",
    "hintExplanation": "Langkahkan Gajah ke c4.",
    "trickExplanation": "Tips Blokh: Harmonisasi empat perwira ringan sebelum meluncurkan operasi ofensif.",
    "xp": 50
  },
  {
    "id": "p58",
    "category": "defense",
    "difficulty": "Sedang",
    "track": "puzzle",
    "fen": "r1bqk2r/pppp1ppp/2n5/4p3/2B1n3/2P2N2/PPP2PPP/R1BQK2R w KQkq - 0 6",
    "turn": "w",
    "solutionUci": "d1d5",
    "solutionSan": "Qd5",
    "motif": "tactic",
    "theme": "Garpu Serangan Balik Menteri (Fork Threat on f7 & e4)",
    "description": "Kuda Hitam memukul e4. Balas dengan manuver Menteri d5 mengancam skakmat di f7 dan memukul Kuda e4!",
    "hintPiece": "Menteri putih di d1.",
    "hintExplanation": "Langkahkan Menteri ke d5 untuk garpuan ganda.",
    "trickExplanation": "Tips Blokh (Double Attack): Ancaman skakmat yang dipadukan dengan ancaman perwira selalu menghasilkan kemenangan material.",
    "xp": 100
  },
  {
    "id": "p59",
    "category": "middlegame",
    "difficulty": "Sedang",
    "track": "puzzle",
    "fen": "r1b2rk1/pp1n1ppp/2p1pn2/q2p4/2PP4/2N1PN2/PP3PPP/R1BQKB1R w KQ - 2 9",
    "turn": "w",
    "solutionUci": "c1d2",
    "solutionSan": "Bd2",
    "motif": "tactic",
    "theme": "Menyiapkan Serangan Terselubung Terhadap Menteri",
    "description": "Menteri Hitam di a5 berhadapan dengan Raja Putih. Tempatkan Gajah di d2 untuk menyiapkan ancaman terbuka.",
    "hintPiece": "Gajah putih di c1.",
    "hintExplanation": "Langkahkan Gajah ke d2.",
    "trickExplanation": "Tips Blokh: Tempatkan perwira berlawanan dengan menteri musuh untuk memicu tembakan terselubung.",
    "xp": 100
  },
  {
    "id": "p60",
    "category": "endgame",
    "difficulty": "Mudah",
    "track": "puzzle",
    "fen": "8/8/8/8/3k4/8/3P4/3K4 w - - 0 1",
    "turn": "w",
    "solutionUci": "d1c2",
    "solutionSan": "Kc2",
    "motif": "tactic",
    "theme": "Manuver Raja Meraih Petak Kunci (Key Squares)",
    "description": "Raja Putih bergerak ke c2 untuk mengamankan jalur maju pion d2.",
    "hintPiece": "Raja putih di d1.",
    "hintExplanation": "Langkahkan Raja ke c2.",
    "trickExplanation": "Tips Blokh: Raja harus melangkah di depan atau di samping pion untuk membuka jalan promosi.",
    "xp": 50
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // BUKU PINTAR CATUR-PEDIA (Fienso Suharsono)
  // BAB 11: JEBAKAN PERMAINAN
  // ═══════════════════════════════════════════════════════════════════════════

  // --- Jebakan Légal (Legal Trap) ---
  // BAB 11 hal. 206: Kuda mengorbankan Menteri untuk skakmat Gajah ganda
  {
    "id": "bp01",
    "category": "jebakan",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4",
    "turn": "w",
    "solutionUci": "f3e5",
    "solutionSan": "Nxe5",
    "motif": "trap",
    "theme": "Jebakan Légal (Légal Trap) · BPCaturPedia Bab 11",
    "description": "Kuda putih mengorbankan diri dengan mengambil pion e5, memancing Kuda hitam untuk meninggalkan pertahanan. Ini adalah langkah pembuka jebakan Légal yang terkenal sejak abad ke-18.",
    "hintPiece": "Kuda putih di f3.",
    "hintExplanation": "Makan pion e5 dengan Kuda. Jika Hitam merespon salah, akan terbuka jalur skakmat kombinasi Gajah.",
    "trickExplanation": "BPCaturPedia Bab 11: Jebakan Légal mengabadikan nama Sire de Légal. Inti jebakan: korbankan Menteri agar Gajah dan Kuda berkolaborasi skakmat. Jika Hitam serakah makan Menteri (Bxd1), maka Bxf7+ Ke7, Nd5# — skakmat cantik dengan Kuda!",
    "xp": 120,
    "source": "bpcaturpedia"
  },

  // --- Jebakan Blackburne Shilling Gambit ---
  // BAB 11 hal. 209: Hitam menjebak putih yang serakah
  {
    "id": "bp02",
    "category": "jebakan",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4",
    "turn": "w",
    "solutionUci": "c4f7",
    "solutionSan": "Bxf7+",
    "motif": "trap",
    "theme": "Serangan Gajah f7 (Shilling Pattern) · BPCaturPedia Bab 11",
    "description": "Gajah putih menyerang titik lemah f7. Di pembukaan, petak f7 (untuk Hitam) dan f2 (untuk Putih) hanya dilindungi oleh Raja — sasaran empuk untuk serangan cepat.",
    "hintPiece": "Gajah putih di c4.",
    "hintExplanation": "Korbankan Gajah ke f7 dengan skak! Raja hitam terpaksa pindah dan kehilangan hak rokade.",
    "trickExplanation": "BPCaturPedia Bab 11: Jebakan Shilling Gambit memanfaatkan kelemahan f7 yang hanya dijaga Raja. Gajah mengorbankan diri di f7+ untuk menghancurkan struktur rokade hitam dan membuka serangan mematikan.",
    "xp": 100,
    "source": "bpcaturpedia"
  },

  // --- Jebakan Lasker (Lasker Trap) ---
  // BAB 11 hal. 218: Promosi bidak menjadi Kuda di langkah ke-7!
  {
    "id": "bp03",
    "category": "jebakan",
    "difficulty": "Sulit",
    "track": "quest",
    "fen": "rnbqkbnr/ppp2ppp/4p3/8/3Pp3/4P3/PPP2PPP/RNBQKBNR b KQkq - 0 3",
    "turn": "b",
    "solutionUci": "f8b4",
    "solutionSan": "Bb4+",
    "motif": "trap",
    "theme": "Jebakan Lasker — Albin Countergambit · BPCaturPedia Bab 11",
    "description": "Hitam melancarkan skak Gajah b4+ sebagai langkah kunci Jebakan Lasker. Ciri khas jebakan ini adalah ancaman promosi bidak menjadi Kuda di langkah ke-7 — sangat tidak lazim namun mematikan!",
    "hintPiece": "Gajah hitam di f8.",
    "hintExplanation": "Keluarkan Gajah ke b4 dengan skak! Ini memaksa Putih merespon dan membuka jalur promosi bidak e3 ke e2-e1.",
    "trickExplanation": "BPCaturPedia Bab 11: Jebakan Lasker berakar dari Albin Countergambit (1.d4 d5 2.c4 e5). Setelah 3.dxe5 d4 4.e3? Bb4+ 5.Bd2 dxe3! 6.Bxb4?? exf2+ 7.Ke2 fxg1=N+!! Promosi menjadi KUDA (bukan Menteri) dengan skak — sungguh fenomenal!",
    "xp": 150,
    "source": "bpcaturpedia"
  },

  // --- Jebakan Magnus Smith ---
  // BAB 11 hal. 222: Pertahanan Sicilia varian Sozin
  {
    "id": "bp04",
    "category": "jebakan",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "r1bqkb1r/pp3p1p/2np1np1/4P3/2B5/2N2N2/PPP2PPP/R1BQK2R w KQkq - 0 8",
    "turn": "w",
    "solutionUci": "e5f6",
    "solutionSan": "exf6",
    "motif": "trap",
    "theme": "Jebakan Magnus Smith — Sicilia Sozin · BPCaturPedia Bab 11",
    "description": "Putih memakan pion f6. Jika hitam merespon dengan salah (misalnya dxe5??), Gajah putih akan memangsa f7 dengan skak dan menangkap Menteri hitam yang terperangkap.",
    "hintPiece": "Pion putih di e5.",
    "hintExplanation": "Makan pion f6! Ini membuka diagonal maut Gajah c4 mengarah ke f7.",
    "trickExplanation": "BPCaturPedia Bab 11: Jebakan Magnus Smith (1869-1934) dalam Sicilia Sozin: setelah 8.e5! dxe5?? 9.Bxf7+! Kxf7 10.Qxd8 — Putih menangkap Menteri hitam. Hitam seharusnya menjawab 8...Ng4 untuk menghindari jebakan.",
    "xp": 120,
    "source": "bpcaturpedia"
  },

  // --- Jebakan Siberia ---
  // BAB 11 hal. 227: Smith-Morra Gambit trap
  {
    "id": "bp05",
    "category": "jebakan",
    "difficulty": "Sulit",
    "track": "quest",
    "fen": "r1b1kb1r/pp1ppppp/2n2n2/q1B5/4P3/2N2N2/PP3PPP/R1BQK2R b KQkq - 0 7",
    "turn": "b",
    "solutionUci": "f6g4",
    "solutionSan": "Ng4",
    "motif": "trap",
    "theme": "Jebakan Siberia — Smith-Morra · BPCaturPedia Bab 11",
    "description": "Kuda hitam melompat ke g4, mengancam garpu Menteri putih dan bidak f2. Ini adalah ciri khas Jebakan Siberia yang menyebabkan Putih kehilangan Menteri.",
    "hintPiece": "Kuda hitam di f6.",
    "hintExplanation": "Loncat ke g4! Ancaman ganda ke f2 dan memaksa Menteri putih terdesak.",
    "trickExplanation": "BPCaturPedia Bab 11: Jebakan Siberia dianalogikan fenomena geologi lava 250 juta tahun lalu. Berakar dari Sicilia Smith-Morra: setelah Ng4, Nd4! mengancam Nxf3 dan Nf2+ secara bersamaan. Putih kehilangan Menteri. Mengabadikan nama Boris Shipkov dari Novosibirsk.",
    "xp": 150,
    "source": "bpcaturpedia"
  },

  // --- Jebakan Rubinstein ---
  // BAB 11 hal. 213: Pertahanan Ortodox
  {
    "id": "bp06",
    "category": "jebakan",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "r1bq1rk1/ppp1bpp1/2np1n1p/4p3/2PPP3/2N1BN2/PP3PPP/R2QKB1R w KQ - 0 8",
    "turn": "w",
    "solutionUci": "c3d5",
    "solutionSan": "Nd5",
    "motif": "trap",
    "theme": "Jebakan Rubinstein — Pembukaan Ortodox · BPCaturPedia Bab 11",
    "description": "Kuda putih melompat ke d5 dengan ancaman ganda. Jika hitam mengambil Kuda, posisi terbuka menguntungkan putih. Jebakan klasik yang membuat hitam kehilangan pion atau perwira.",
    "hintPiece": "Kuda putih di c3.",
    "hintExplanation": "Loncat ke d5! Posisi sentral dominan yang mengancam banyak potongan hitam.",
    "trickExplanation": "BPCaturPedia Bab 11: Jebakan Rubinstein dari partai Euwe vs Rubinstein, Bad Kissingen 1928. Setelah Nd5, jika Nxf4 maka Nxf4 kehilangan bidak. Jika cxd5 maka Bc7 — Menteri hitam terjebak buah catur sendiri di belakang!",
    "xp": 120,
    "source": "bpcaturpedia"
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // BUKU PINTAR CATUR-PEDIA (Fienso Suharsono)
  // BAB 12: TAKTIK SKAK MAT (Pola Skakmat Terkenal)
  // ═══════════════════════════════════════════════════════════════════════════

  // --- Skak Mat Anastasia ---
  // BAB 12 hal. 268
  {
    "id": "bp07",
    "category": "skakmat",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "4rrk1/1b3ppp/pq2p3/1p2N3/3P4/P7/1P3PPP/R2QR1K1 w - - 0 1",
    "turn": "w",
    "solutionUci": "e5f7",
    "solutionSan": "Nxf7",
    "motif": "mate",
    "theme": "Pola Skakmat Anastasia · BPCaturPedia Bab 12",
    "description": "Kuda putih mengorbankan diri di f7 untuk membuka jalur skakmat Benteng. Pola Anastasia: Kuda dan Benteng bekerja sama menjebak Raja di tepi papan.",
    "hintPiece": "Kuda putih di e5.",
    "hintExplanation": "Korbankan Kuda ke f7! Setelah Raja mengambil, Benteng akan skak di lajur-e yang terbuka.",
    "trickExplanation": "BPCaturPedia Bab 12: Pola Skakmat Anastasia menggunakan kombinasi Kuda dan Benteng. Kuda mengontrol petak-petak pelarian Raja, sementara Benteng memberikan skakmat dari jarak jauh. Dinamai dari novel 'Anastasia und das Schachspiel' (1803).",
    "xp": 120,
    "source": "bpcaturpedia"
  },

  // --- Skak Mat Baris Belakang (Back Rank Mate) ---
  // BAB 12 hal. 269
  {
    "id": "bp08",
    "category": "skakmat",
    "difficulty": "Mudah",
    "track": "quest",
    "fen": "6k1/5ppp/8/8/8/8/5PPP/1R4K1 w - - 0 1",
    "turn": "w",
    "solutionUci": "b1b8",
    "solutionSan": "Rb8#",
    "motif": "mate",
    "theme": "Skakmat Kolom Belakang (Back Rank Mate) · BPCaturPedia Bab 12",
    "description": "Benteng putih menerobos ke baris ke-8. Raja hitam terkurung di belakang pion-pion sendiri — tidak ada jalan keluar!",
    "hintPiece": "Benteng putih di b1.",
    "hintExplanation": "Langkahkan Benteng ke b8. Raja terkunci di belakang dinding pion g7, f7, h7.",
    "trickExplanation": "BPCaturPedia Bab 12: Skakmat Kolom Belakang adalah pola paling sering terjadi di permainan praktis. Raja terjebak di belakang pion-pion sendiri (pion g7, f7, h7 menghalangi pelarian). Solusi pencegahan: buat 'lubang udara' (luft) dengan h6 atau g6.",
    "xp": 50,
    "source": "bpcaturpedia"
  },

  // --- Skak Mat Boden ---
  // BAB 12 hal. 271
  {
    "id": "bp09",
    "category": "skakmat",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "2kr4/ppp2p2/2n5/4B3/8/2b5/PPP2PPP/R4RK1 w - - 0 1",
    "turn": "w",
    "solutionUci": "e5a1",
    "solutionSan": "Ba1",
    "motif": "mate",
    "theme": "Skakmat Boden (Boden's Mate) · BPCaturPedia Bab 12",
    "description": "Dua Gajah menyilang diagonal untuk mengepung Raja yang terkurung di rokade panjang. Pola Boden: diagonal ganda menembus pertahanan pion.",
    "hintPiece": "Gajah putih di e5.",
    "hintExplanation": "Tempatkan Gajah ke diagonal panjang untuk menyerang Raja bersama Gajah hitam di c3.",
    "trickExplanation": "BPCaturPedia Bab 12: Skakmat Boden menggunakan dua Gajah yang menyilang diagonal untuk mengepung Raja. Biasanya terjadi setelah Raja rokade panjang dengan pion-pion di c7 dan b7/a7 menghalangi pelarian. Nama ini mengabadikan Samuel Boden.",
    "xp": 120,
    "source": "bpcaturpedia"
  },

  // --- Skak Mat Damiano ---
  // BAB 12 hal. 273
  {
    "id": "bp10",
    "category": "skakmat",
    "difficulty": "Mudah",
    "track": "quest",
    "fen": "5rk1/5ppp/8/8/8/8/4RPPP/6K1 w - - 0 1",
    "turn": "w",
    "solutionUci": "e2e8",
    "solutionSan": "Re8",
    "motif": "mate",
    "theme": "Skakmat Damiano · BPCaturPedia Bab 12",
    "description": "Benteng putih menerobos ke baris belakang. Pola Damiano: Menteri atau Benteng skakmat di baris ke-8 setelah pertukaran paksa.",
    "hintPiece": "Benteng putih di e2.",
    "hintExplanation": "Dorong Benteng ke e8! Tukar Benteng lawan dan skakmat kombinasi baris belakang.",
    "trickExplanation": "BPCaturPedia Bab 12: Pola Damiano dinamai pecatur Italia Pedro Damiano (1480-1544). Inti pola: Menteri atau Benteng mengorbankan diri untuk membersihkan baris belakang, lalu perwira kedua mengeksekusi skakmat.",
    "xp": 50,
    "source": "bpcaturpedia"
  },

  // --- Skak Mat Dicekik (Smothered Mate) ---
  // BAB 12 hal. 274
  {
    "id": "bp11",
    "category": "skakmat",
    "difficulty": "Sulit",
    "track": "quest",
    "fen": "r1b3kr/ppp2Npp/2n5/3B4/8/8/PPP2PPP/R3K2R w KQ - 0 1",
    "turn": "w",
    "solutionUci": "f7h6",
    "solutionSan": "Nh6+",
    "motif": "mate",
    "theme": "Skakmat Dicekik (Smothered Mate) · BPCaturPedia Bab 12",
    "description": "Kuda putih memberikan skak di h6. Raja hitam 'dicekik' oleh buah catur sendiri — terkurung tanpa ada petak pelarian! Pola yang sangat elegan.",
    "hintPiece": "Kuda putih di f7.",
    "hintExplanation": "Skak di h6! Raja terkurung oleh Benteng h8, pion g7 dan h7 sendiri.",
    "trickExplanation": "BPCaturPedia Bab 12: Skakmat Dicekik (Smothered Mate) terjadi ketika Raja tidak bisa bergerak karena dikelilingi buah catur sendiri. Hanya Kuda yang bisa melakukan ini karena kemampuannya melompati bidak lain. Pola ini juga disebut 'Philidor's Legacy'.",
    "xp": 150,
    "source": "bpcaturpedia"
  },

  // --- Skak Mat Epaulette ---
  // BAB 12 hal. 275
  {
    "id": "bp12",
    "category": "skakmat",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "3r1rk1/pp3ppp/8/3Q4/8/8/PPP2PPP/R5K1 w - - 0 1",
    "turn": "w",
    "solutionUci": "d5f7",
    "solutionSan": "Qxf7+",
    "motif": "mate",
    "theme": "Skakmat Epaulette · BPCaturPedia Bab 12",
    "description": "Menteri putih memangsa pion f7 dengan skak. Kedua Benteng hitam di d8 dan f8 menghalangi Raja seperti 'epaulette' (tanda pangkat bahu militer) — Raja tak bisa ke mana-mana!",
    "hintPiece": "Menteri putih di d5.",
    "hintExplanation": "Ambil pion f7 dengan skak! Benteng di d8 dan f8 justru mengurung Raja sendiri.",
    "trickExplanation": "BPCaturPedia Bab 12: Skakmat Epaulette dinamai karena dua buah catur di samping kiri-kanan Raja mirip tanda pangkat militer (epaulette) di bahu. Kunci: Menteri atau perwira menyerang, sementara dua Benteng/perwira sendiri menghalangi Raja melarikan diri ke samping.",
    "xp": 120,
    "source": "bpcaturpedia"
  },

  // --- Skak Mat Greco ---
  // BAB 12 hal. 276
  {
    "id": "bp13",
    "category": "skakmat",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "r1bq1rk1/ppppbppp/2n2n2/4p3/2B1P3/2N2N2/PPPP1PPP/R1BQ1RK1 w - - 6 5",
    "turn": "w",
    "solutionUci": "f3g5",
    "solutionSan": "Ng5",
    "motif": "tactic",
    "theme": "Pengorbanan Greco (Greco's Sacrifice) · BPCaturPedia Bab 12",
    "description": "Kuda putih melompat ke g5, mengancam f7 dan mempersiapkan pengorbanan klasik Gajah di h7. Pola Greco: Bxh7+ diikuti Ng5+ dan Menteri masuk melalui h5.",
    "hintPiece": "Kuda putih di f3.",
    "hintExplanation": "Lompat ke g5! Ini mempersiapkan serangan klasik Greco: Bxh7+ Kxh7, Ng5+ dan Qh5.",
    "trickExplanation": "BPCaturPedia Bab 12: Pengorbanan Greco dinamai Gioachino Greco (1600-1634), pecatur Italia legendaris. Pola: 1) Bxh7+! Kxh7 2) Ng5+ Kg8/Kg6 3) Qh5 — serangan mematikan ke Raja yang terbuka. Ini salah satu kombinasi paling terkenal sepanjang sejarah catur.",
    "xp": 120,
    "source": "bpcaturpedia"
  },

  // --- Skak Mat Morphy ---
  // BAB 12 hal. 282
  {
    "id": "bp14",
    "category": "skakmat",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "r1b1k2r/pppp1ppp/2n2n2/2b1p3/2B1P3/3P1N2/PPP2PPP/RNBQK2R w KQkq - 4 4",
    "turn": "w",
    "solutionUci": "c1g5",
    "solutionSan": "Bg5",
    "motif": "tactic",
    "theme": "Pola Morphy — Serangan Gajah Pin · BPCaturPedia Bab 12",
    "description": "Gajah putih ke g5 memaku (pin) Kuda f6 terhadap Menteri d8. Pola khas Paul Morphy: pengembangan perwira cepat + pin mematikan.",
    "hintPiece": "Gajah putih di c1.",
    "hintExplanation": "Keluarkan Gajah ke g5! Pin Kuda f6 terhadap Menteri — posisi taktis sangat kuat.",
    "trickExplanation": "BPCaturPedia Bab 12: Pola Morphy mengabadikan Paul Morphy (1837-1884), jenius catur Amerika. Prinsip utama: kembangkan semua perwira secepat mungkin, buat pin dan ancaman sebelum lawan siap. Bg5 memaku Kuda dan mengganggu koordinasi hitam.",
    "xp": 100,
    "source": "bpcaturpedia"
  },

  // --- Skak Mat Pillsbury ---
  // BAB 12 hal. 283
  {
    "id": "bp15",
    "category": "skakmat",
    "difficulty": "Sulit",
    "track": "quest",
    "fen": "r4rk1/pp1b1ppp/1qn1pn2/2ppN3/3P1B2/2PBPN2/PP3PPP/R2Q1RK1 w - - 0 10",
    "turn": "w",
    "solutionUci": "e5g6",
    "solutionSan": "Nxg6",
    "motif": "tactic",
    "theme": "Pola Pillsbury — Serangan Sayap Raja · BPCaturPedia Bab 12",
    "description": "Kuda putih mengorbankan diri di g6 untuk menghancurkan perisai pion Raja hitam. Pola Pillsbury: Kuda outpost + serangan perwira berat ke sayap Raja.",
    "hintPiece": "Kuda putih di e5.",
    "hintExplanation": "Korbankan di g6! Hancurkan struktur pion Raja dan buka jalur serangan Menteri dan Gajah.",
    "trickExplanation": "BPCaturPedia Bab 12: Pola Pillsbury mengabadikan Harry Nelson Pillsbury (1872-1906). Strateginya: pasang Kuda dominan di e5, Gajah di d3 mengincar h7, Menteri siap masuk via h5. Setelah Nxg6 fxg6/hxg6, pion Raja hancur dan serangan mematikan meluncur.",
    "xp": 150,
    "source": "bpcaturpedia"
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // BUKU PINTAR CATUR-PEDIA (Fienso Suharsono)
  // BAB 7: TAKTIK CATUR (Latihan Pola Taktik)
  // ═══════════════════════════════════════════════════════════════════════════

  // --- Taktik Garpu / Fork (Bab 7 hal. 77) ---
  {
    "id": "bp16",
    "category": "middlegame",
    "difficulty": "Mudah",
    "track": "quest",
    "fen": "r1bqkb1r/pppp1ppp/2n5/4p3/3nP3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 4",
    "turn": "w",
    "solutionUci": "d1e2",
    "solutionSan": "Qe2",
    "motif": "tactic",
    "theme": "Taktik Garpu — Serangan Ganda (Fork) · BPCaturPedia Bab 7",
    "description": "Menteri putih pindah ke e2 mengancam Kuda d4 dan mempertahankan pion e4. Taktik garpu membuat lawan harus memilih buah mana yang diselamatkan.",
    "hintPiece": "Menteri putih di d1.",
    "hintExplanation": "Pindahkan Menteri ke e2 — serangan ganda ke Kuda dan pertahanan pusat.",
    "trickExplanation": "BPCaturPedia Bab 7: Taktik Garpu (Fork) adalah menyerang dua atau lebih sasaran secara bersamaan. Lawan dipaksa kehilangan salah satu buah catur. Kuda paling sering membuat garpu karena langkahnya sulit diantisipasi.",
    "xp": 80,
    "source": "bpcaturpedia"
  },

  // --- Taktik Tusuk Sate / Skewer (Bab 7 hal. 80) ---
  {
    "id": "bp17",
    "category": "middlegame",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "r3k2r/ppp2ppp/2n1bn2/3pp3/8/2N1B3/PPPQBPPP/R3K2R w KQkq - 0 8",
    "turn": "w",
    "solutionUci": "e2b5",
    "solutionSan": "Bb5",
    "motif": "tactic",
    "theme": "Taktik Tusuk Sate (Skewer) · BPCaturPedia Bab 7",
    "description": "Gajah putih ke b5 menyerang Raja hitam yang berada di garis dengan Benteng a8. Tusuk Sate: buah berharga dipaksa pindah, mengekspos buah di belakangnya!",
    "hintPiece": "Gajah putih di e2.",
    "hintExplanation": "Arahkan Gajah ke b5! Skak Raja lalu setelah pindah, Benteng di a8 jadi sasaran.",
    "trickExplanation": "BPCaturPedia Bab 7: Taktik Tusuk Sate (Skewer) adalah kebalikan dari Pin. Buah bernilai tinggi (Raja/Menteri) diserang di depan, dipaksa pindah, sehingga buah di belakangnya tertangkap. Mirip tusuk sate: menusuk dua bahan sekaligus!",
    "xp": 100,
    "source": "bpcaturpedia"
  },

  // --- Taktik Umpan / Decoy (Bab 7 hal. 84) ---
  {
    "id": "bp18",
    "category": "middlegame",
    "difficulty": "Sedang",
    "track": "quest",
    "fen": "5rk1/pp3ppp/8/8/8/8/PPR2PPP/4R1K1 w - - 0 1",
    "turn": "w",
    "solutionUci": "e1e8",
    "solutionSan": "Re8",
    "motif": "mate",
    "theme": "Taktik Umpan (Decoy) + Skakmat · BPCaturPedia Bab 7",
    "description": "Benteng putih mengorbankan diri di e8 sebagai umpan. Jika Raja mengambil (Rxe8), Benteng c2 maju ke c8 — skakmat baris belakang! Memaksa lawan ke posisi fatal.",
    "hintPiece": "Benteng putih di e1.",
    "hintExplanation": "Korbankan Benteng ke e8! Setelah Rxe8, Rc8# skakmat baris belakang.",
    "trickExplanation": "BPCaturPedia Bab 7: Taktik Umpan (Decoy) memaksa lawan berpindah ke tempat yang riskan dan berbahaya. Seperti dijelaskan: 'memaksa lawan ke petak yang menjebak'. Benteng dikorbankan agar Raja masuk ke perangkap skakmat.",
    "xp": 100,
    "source": "bpcaturpedia"
  }
];
