const fs = require('fs');
const path = require('path');
const { Chess } = require('chess.js');

const rawPuzzles = [
  // 1-12: OPENING (Pembukaan & Jebakan Populer)
  {
    id: 'p01',
    category: 'opening',
    difficulty: 'Mudah',
    fen: 'r1bqkb1r/pppp1ppp/2n5/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 0 4',
    turn: 'w',
    solutionUci: 'h5f7',
    theme: "Skakmat Scholar (Scholar's Mate)",
    description: 'Manfaatkan titik lemah petak f7 yang hanya dijaga oleh raja Hitam di fase awal pembukaan.',
    hintPiece: 'Menteri putih di petak h5.',
    hintExplanation: 'Menteri memukul bidak di f7 dengan bantuan perlindungan Gajah c4 untuk skakmat langsung.',
    trickExplanation: 'Trik Titik Lemah f7: Sebelum rokade, petak f7 adalah titik paling rentan karena hanya dijaga oleh Raja.',
  },
  {
    id: 'p02',
    category: 'opening',
    difficulty: 'Mudah',
    fen: 'rnbqkbnr/ppppp1pp/5p2/8/4P3/6P1/PPPP1P1P/RNBQKBNR w KQkq - 0 2',
    turn: 'w',
    solutionUci: 'd1h5',
    theme: "Celah Diagonal Maut (Fool's Pattern)",
    description: 'Hitam melangkahkan f6 di langkah pembuka. Manfaatkan celah diagonal raja e8-h5.',
    hintPiece: 'Menteri putih di petak d1.',
    hintExplanation: 'Luncurkan Menteri ke h5 untuk memberikan skak keras pada raja Hitam.',
    trickExplanation: 'Mendorong pion f di awal permainan merusak benteng perlindungan diagonal raja.',
  },
  {
    id: 'p03',
    category: 'opening',
    difficulty: 'Sedang',
    fen: 'r1bqkb1r/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 2 4',
    turn: 'w',
    solutionUci: 'f3g5',
    theme: 'Serangan Hati Ayam (Fried Liver Attack)',
    description: 'Tekan titik f7 bersama Gajah c4 sebelum Hitam menyelesaikan perkembangan perwira ringannya.',
    hintPiece: 'Kuda putih di petak f3.',
    hintExplanation: 'Langkahkan Kuda f3 ke g5 untuk menambah ancaman ganda ke petak f7.',
    trickExplanation: 'Kombinasi Kuda g5 dan Gajah c4 mengancam petak f7 secara simultan.',
  },
  {
    id: 'p04',
    category: 'opening',
    difficulty: 'Sedang',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 4',
    turn: 'b',
    solutionUci: 'f6e4',
    theme: 'Garpu Pusat Kuda (Center Fork Trick)',
    description: 'Hitam memukul pion e4 untuk merebut inisiatif pusat lewat garpuan d7-d5 pada langkah berikutnya.',
    hintPiece: 'Kuda hitam di petak f6.',
    hintExplanation: 'Pukul pion e4 dengan Kuda hitam.',
    trickExplanation: 'Jika Putih membalas Nxe4, Hitam membalas d7-d5 menggarpu Gajah dan Kuda putih.',
  },
  {
    id: 'p05',
    category: 'opening',
    difficulty: 'Sulit',
    fen: 'r2qkb1r/pp1n1ppp/2p5/4N3/2B1P3/8/PPPP1PPP/RNBbK2R w KQkq - 0 8',
    turn: 'w',
    solutionUci: 'c4f7',
    theme: "Jebakan Legal (Legal's Trap Finale)",
    description: 'Hitam tergiur memakan Menteri Putih di d1. Hukum kecerobohan lawan dengan skak pengorbanan gajah!',
    hintPiece: 'Gajah putih di c4.',
    hintExplanation: 'Pukul bidak f7 dengan Gajah untuk skak dan memaksa Raja Hitam melangkah ke e7.',
    trickExplanation: "Legal's Mate adalah jebakan klasik di mana pengorbanan Menteri berbuah skakmat cepat.",
  },
  {
    id: 'p06',
    category: 'opening',
    difficulty: 'Sedang',
    fen: 'r1bqkb1r/pp1npppp/2p2n2/8/3PN3/8/PPP1QPPP/R1B1KBNR w KQkq - 1 6',
    turn: 'w',
    solutionUci: 'e4d6',
    theme: 'Skakmat Tercekik Caro-Kann',
    description: 'Hitam memblokir petak pelarian raja. Manfaatkan pin mutlak Menteri e2 terhadap pion e7!',
    hintPiece: 'Kuda putih di petak e4.',
    hintExplanation: 'Lompatkan Kuda ke d6 untuk skakmat mutlak karena pion e7 ter-pin oleh Menteri e2.',
    trickExplanation: 'Pion e7 tidak dapat memukul d6 karena raja Hitam akan langsung terbuka terhadap Menteri putih.',
  },
  {
    id: 'p07',
    category: 'opening',
    difficulty: 'Sedang',
    fen: 'r1b1k2r/ppppqppp/2n5/4n3/1PP5/5N2/1P1NPPPP/R2QKB1R b KQkq - 0 8',
    turn: 'b',
    solutionUci: 'e5d3',
    theme: 'Skakmat Budapest Gambit',
    description: 'Putih lengah memakan perwira di b4. Luncurkan Kuda hitam untuk menyelesaikan duel seketika!',
    hintPiece: 'Kuda hitam di petak e5.',
    hintExplanation: 'Lompatkan Kuda ke d3 untuk skakmat karena pion e2 ter-pin oleh Menteri e7.',
    trickExplanation: 'Budapest Gambit menghukum kelemahan pion e2 dengan skakmat Kuda elegan.',
  },
  {
    id: 'p08',
    category: 'opening',
    difficulty: 'Sedang',
    fen: 'r1bqkb1r/pppn1ppp/5n2/3N2B1/3P4/8/PP2PPPP/R2QKBNR b KQkq - 0 6',
    turn: 'b',
    solutionUci: 'f6d5',
    theme: "Jebakan Gajah Queen's Gambit (Elephant Trap)",
    description: 'Putih baru saja memukul d5 dengan Kuda. Balas dengan memukul kuda tersebut!',
    hintPiece: 'Kuda hitam di f6.',
    hintExplanation: 'Pukul Kuda d5 dengan Kuda f6. Jika Putih memakan menteri d8, Hitam membalas Bb4+!',
    trickExplanation: 'Elephant Trap: Hitam membiarkan menterinya diserang karena skak Bb4+ akan merebut kembali menteri lawan plus untung 1 perwira.',
  },
  {
    id: 'p09',
    category: 'opening',
    difficulty: 'Mudah',
    fen: 'rnbqkbnr/pppp1ppp/8/4p3/4PP2/8/PPPP2PP/RNBQKBNR b KQkq - 0 2',
    turn: 'b',
    solutionUci: 'd8h4',
    theme: "Skak Serangan Balik King's Gambit",
    description: 'Putih membuka jalur sayap raja f2-f4 secara terburu-buru. Balas dengan serangan cepat!',
    hintPiece: 'Menteri hitam di petak d8.',
    hintExplanation: 'Langkahkan Menteri ke h4 untuk memberikan skak keras pada raja putih.',
    trickExplanation: 'Menyerang diagonal sayap raja yang terbuka melemahkan koordinasi Putih sejak awal laga.',
  },
  {
    id: 'p10',
    category: 'opening',
    difficulty: 'Sulit',
    fen: 'r1b1kbnr/pppp1ppp/8/4n3/3PP2q/8/PPP2PPP/RNBQKBNR w KQkq - 1 5',
    turn: 'w',
    solutionUci: 'd4e5',
    theme: 'Menghukum Manuver Menteri Terlalu Dini',
    description: 'Hitam melancarkan serangan menteri prematur dan meninggalkan Kuda di e5 tanpa perlindungan.',
    hintPiece: 'Pion putih di petak d4.',
    hintExplanation: 'Pukul Kuda hitam di e5 secara gratis dengan pion d4.',
    trickExplanation: 'Menteri yang keluar terlalu awal sering menelantarkan perwira rekannya tanpa pengawalan.',
  },
  {
    id: 'p11',
    category: 'opening',
    difficulty: 'Mudah',
    fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 4 5',
    turn: 'w',
    solutionUci: 'e1g1',
    theme: 'Rokade Dini Mengamankan Raja',
    description: 'Selesaikan tahap pembukaan dengan mengamankan Raja di sudut dan mengaktifkan Benteng.',
    hintPiece: 'Raja putih di petak e1.',
    hintExplanation: 'Lakukan rokade sayap raja (O-O) untuk menuntaskan koordinasi pertahanan.',
    trickExplanation: 'Rokade cepat melindungi raja dari serangan taktis tak terduga di jalur tengah.',
  },
  {
    id: 'p12',
    category: 'opening',
    difficulty: 'Sedang',
    fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/3PP3/5N2/PPP2PPP/RNBQKB1R b KQkq - 0 3',
    turn: 'b',
    solutionUci: 'e5d4',
    theme: 'Pembongkaran Pusat Scotch Game',
    description: 'Putih menekan pusat di d4. Pukul pion pusat untuk mempertahankan kesetaraan material.',
    hintPiece: 'Pion hitam di petak e5.',
    hintExplanation: 'Pukul pion d4 dengan pion e5.',
    trickExplanation: 'Mempertukarkan pion pusat mencegah Putih menguasai ruang di wilayah pembukaan.',
  },

  // 13-24: DEFENSE & COUNTER-ATTACK (Pertahanan & Serangan Balik)
  {
    id: 'p13',
    category: 'defense',
    difficulty: 'Sedang',
    fen: 'r1b1k2r/pp1pqppp/2n5/8/8/8/PPPP1PPP/R1BQR1K1 w kq - 0 1',
    turn: 'w',
    solutionUci: 'e1e7',
    theme: 'Pin Mutlak Jalur Terbuka (Absolute Pin)',
    description: 'Menteri hitam di e7 terkena pin mutlak terhadap raja di e8. Rebut materi gratis!',
    hintPiece: 'Benteng putih di petak e1.',
    hintExplanation: 'Pukul Menteri lawan di e7 secara cuma-cuma karena menteri ter-pin terhadap raja.',
    trickExplanation: 'Bidak yang ter-pin ke raja dilarang melangkah menurut hukum resmi catur.',
  },
  {
    id: 'p14',
    category: 'defense',
    difficulty: 'Mudah',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/4P3/3P1N2/PPP2PPP/RNBQKB1R w KQkq - 1 4',
    turn: 'w',
    solutionUci: 'c1g5',
    theme: 'Pin Sayap Gajah (Flank Pin)',
    description: 'Kunci pergerakan Kuda hitam di f6 terhadap Menterinya di d8 untuk meredam inisiatif lawan.',
    hintPiece: 'Gajah putih di petak c1.',
    hintExplanation: 'Kembangkan Gajah ke g5 untuk mem-pin Kuda f6.',
    trickExplanation: 'Mem-pin kuda ke menteri lawan membatasi mobilitas taktis mereka.',
  },
  {
    id: 'p15',
    category: 'defense',
    difficulty: 'Mudah',
    fen: '4r1k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1',
    turn: 'w',
    solutionUci: 'e1e8',
    theme: 'Pertahanan Aktif Baris Belakang',
    description: 'Benteng hitam menekan baris belakang Anda. Netralkan ancaman dengan skakmat balik!',
    hintPiece: 'Benteng putih di e1.',
    hintExplanation: 'Pukul Benteng lawan di e8 untuk skakmat baris terakhir.',
    trickExplanation: 'Pertahanan terbaik seringkali adalah serangan balik langsung yang menuntaskan partai.',
  },
  {
    id: 'p16',
    category: 'defense',
    difficulty: 'Sedang',
    fen: 'r2q1rk1/ppp2ppp/2n1bn2/3p4/3P4/2PB1N2/PP1N1PPP/R2Q1RK1 w - - 0 10',
    turn: 'w',
    solutionUci: 'd1c2',
    theme: 'Baterai Menteri & Gajah (Battery Formation)',
    description: 'Bentuk formasi baterai Menteri-Gajah yang mengincar sayap raja Hitam di petak h7.',
    hintPiece: 'Menteri putih di d1.',
    hintExplanation: 'Langkahkan Menteri ke c2 untuk mengunci jalur diagonal b1-h7.',
    trickExplanation: 'Baterai perwira berat dan ringan menciptakan tekanan taktis masif ke kubu pertahanan lawan.',
  },
  {
    id: 'p17',
    category: 'defense',
    difficulty: 'Sulit',
    fen: '2r3k1/5ppp/8/8/8/8/1q3PPP/4R1K1 b - - 0 1',
    turn: 'b',
    solutionUci: 'c8c1',
    theme: 'Pin Benteng Baris Pertama',
    description: 'Putih meninggalkan baris pertama tanpa pertahanan cukup. Kunci benteng putih!',
    hintPiece: 'Benteng hitam di c8.',
    hintExplanation: 'Langkahkan Benteng ke c1 untuk mem-pin dan memenangkan Benteng putih.',
    trickExplanation: 'Kelemahan baris dasar (back rank) dapat dimanfaatkan dengan memasukkan benteng aktif.',
  },
  {
    id: 'p18',
    category: 'defense',
    difficulty: 'Sedang',
    fen: 'r4rk1/pp1b1ppp/2n1p3/3pP3/3P4/2PB1N2/P4PPP/R4RK1 w - - 0 14',
    turn: 'w',
    solutionUci: 'd3h7',
    theme: 'Pengorbanan Hadiah Yunani (Greek Gift Sacrifice)',
    description: 'Benteng sayap raja Hitam terkunci. Korbankan Gajah di h7 untuk membongkar pertahanan Raja!',
    hintPiece: 'Gajah putih di d3.',
    hintExplanation: 'Pukul pion h7 dengan Gajah untuk skak dan memancing Raja ke petak terbuka.',
    trickExplanation: 'Greek Gift adalah pengorbanan klasik gajah di h7/h2 untuk melancarkan serangan matil Kuda dan Menteri.',
  },
  {
    id: 'p19',
    category: 'defense',
    difficulty: 'Mudah',
    fen: 'r1bqk2r/ppppbppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
    turn: 'w',
    solutionUci: 'd2d3',
    theme: 'Soliditas Rantai Pion Pusat',
    description: 'Perkuat pion e4 dan buka jalur diagonal untuk Gajah petak terang c1.',
    hintPiece: 'Pion putih di petak d2.',
    hintExplanation: 'Dorong pion d2 ke d3.',
    trickExplanation: 'Rantai pion yang kokoh menopang perwira dan mencegah infiltrasi taktik lawan.',
  },
  {
    id: 'p20',
    category: 'defense',
    difficulty: 'Sedang',
    fen: 'r1b1qrk1/ppp2ppp/2np1n2/2b1p3/2B1P3/2NP1N2/PPP1QPPP/R1B2RK1 w - - 0 8',
    turn: 'w',
    solutionUci: 'c1g5',
    theme: 'Penekanan Pin Kuda Sayap Raja',
    description: 'Tingkatkan tekanan pada titik f6 untuk merusak struktur pion sayap raja lawan.',
    hintPiece: 'Gajah putih di c1.',
    hintExplanation: 'Langkahkan Gajah ke g5 untuk mem-pin Kuda f6.',
    trickExplanation: 'Menghancurkan struktur pion perlindungan raja musuh membuka jalur serangan akhir.',
  },
  {
    id: 'p21',
    category: 'defense',
    difficulty: 'Mudah',
    fen: 'r1bqk2r/pppp1ppp/2n5/4p3/1b2P3/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 1 6',
    turn: 'w',
    solutionUci: 'c1d2',
    theme: 'Menetralisir Pin pada Kuda',
    description: 'Gajah hitam mem-pin Kuda c3 ke Raja. Tutup pin tersebut dengan Gajah Anda!',
    hintPiece: 'Gajah putih di petak c1.',
    hintExplanation: 'Langkahkan Gajah ke d2 untuk melindungi Kuda dan menghilangkan ancaman pin.',
    trickExplanation: 'Menetralisir pin mengembalikan kebebasan pergerakan perwira bertahan.',
  },
  {
    id: 'p22',
    category: 'defense',
    difficulty: 'Sedang',
    fen: 'r2q1rk1/1pp2ppp/p1np1n2/2b1p1B1/2B1P1b1/2NP1N2/PPP1QPPP/R4RK1 w - - 2 9',
    turn: 'w',
    solutionUci: 'c3d5',
    theme: 'Pemberian Tekanan Berlipat (Double Pressure)',
    description: 'Manfaatkan Kuda f6 yang ter-pin dengan menaruh Kuda c3 di pos terdepan d5!',
    hintPiece: 'Kuda putih di c3.',
    hintExplanation: 'Lompatkan Kuda ke petak d5 untuk menambah penyerang ke titik f6.',
    trickExplanation: 'Menambah penyerang pada bidak yang ter-pin seringkali memaksa keruntuhan pertahanan lawan.',
  },
  {
    id: 'p23',
    category: 'defense',
    difficulty: 'Sulit',
    fen: '3r2k1/p4ppp/1p6/8/8/1P6/P4PPP/4R1K1 b - - 0 1',
    turn: 'b',
    solutionUci: 'g7g6',
    theme: 'Membuat Lubang Angin Raja (Luft)',
    description: 'Cegah ancaman skakmat baris belakang dengan membuka petak pelarian g7 untuk Raja!',
    hintPiece: 'Pion hitam di petak g7.',
    hintExplanation: 'Dorong pion g7 ke g6 untuk memberi ruang bernapas bagi Raja di baris dasar.',
    trickExplanation: 'Membuat "Luft" adalah prinsip pencegahan paling krusial sebelum melancarkan serangan benteng.',
  },
  {
    id: 'p24',
    category: 'defense',
    difficulty: 'Sedang',
    fen: 'r1bq1rk1/ppp2ppp/2n1pn2/3p4/2PP4/2N1PN2/PP3PPP/R1BQKB1R w KQ - 0 6',
    turn: 'w',
    solutionUci: 'c4d5',
    theme: 'Penyederhanaan Struktur Pion Pusat',
    description: 'Buka jalur c untuk Benteng dengan memukul pion d5.',
    hintPiece: 'Pion putih di c4.',
    hintExplanation: 'Pukul pion d5 dengan pion c4.',
    trickExplanation: 'Pertukaran pion membuka jalur terbuka bagi benteng untuk bermanuver aktif.',
  },

  // 25-38: MIDDLEGAME TACTICS (Taktik Babak Tengah)
  {
    id: 'p25',
    category: 'middlegame',
    difficulty: 'Mudah',
    fen: 'r1b1k2r/pppp1ppp/8/4q3/1bP5/2N1P3/PP1B1PPP/R2QKB1R w KQkq - 0 9',
    turn: 'w',
    solutionUci: 'd1a4',
    theme: 'Garpu Menteri (Double Attack)',
    description: 'Menteri putih dapat menyerang Raja dan Gajah hitam sekaligus dari petak a4.',
    hintPiece: 'Menteri putih di petak d1.',
    hintExplanation: 'Langkahkan Menteri ke a4 untuk skak dan memenangkan Gajah b4.',
    trickExplanation: 'Serangan ganda menteri merebut materi perwira yang tidak dijaga.',
  },
  {
    id: 'p26',
    category: 'middlegame',
    difficulty: 'Sedang',
    fen: '2r2rk1/pb3ppp/1p2p3/n3N3/3P4/q1PBP3/P3QPPP/2R2RK1 w - - 0 16',
    turn: 'w',
    solutionUci: 'd3h7',
    theme: 'Pembongkaran Hadiah Yunani Klasik',
    description: 'Korbankan gajah di h7 untuk menarik keluar Raja lawan ke petak terbuka!',
    hintPiece: 'Gajah putih di d3.',
    hintExplanation: 'Pukul pion h7 dengan Gajah untuk skak keras.',
    trickExplanation: 'Pengorbanan di h7 membuka jalan bagi Menteri h5 dan Kuda g5 memburu raja.',
  },
  {
    id: 'p27',
    category: 'middlegame',
    difficulty: 'Mudah',
    fen: 'r1b2rk1/ppp2ppp/8/3N4/3q4/3B4/PPP2PPP/R2Q1RK1 w - - 0 12',
    turn: 'w',
    solutionUci: 'd3h7',
    theme: 'Serangan Terbuka Rebut Menteri (Discovered Attack)',
    description: 'Manfaatkan skak terbuka gajah di h7 untuk memenangkan Menteri hitam di d4!',
    hintPiece: 'Gajah putih di petak d3.',
    hintExplanation: 'Pukul pion h7 dengan gajah untuk skak. Menteri putih di d1 akan memakan menteri hitam di d4!',
    trickExplanation: 'Serangan terbuka (discovered attack) adalah salah satu senjata taktis paling mematikan dalam catur.',
  },
  {
    id: 'p28',
    category: 'middlegame',
    difficulty: 'Sedang',
    fen: 'r4rk1/1pp2ppp/p1np4/4p3/B3P1n1/2PPP1qP/PP1N2P1/R2QR1K1 b - - 0 15',
    turn: 'b',
    solutionUci: 'g3h2',
    theme: 'Infiltrasi Menteri ke Sayap Raja',
    description: 'Luncurkan Menteri hitam ke h2 untuk menekan Raja putih ke sudut petak f1!',
    hintPiece: 'Menteri hitam di petak g3.',
    hintExplanation: 'Langkahkan Menteri ke h2 untuk skak didukung Kuda g4.',
    trickExplanation: 'Kerjasama Menteri dan Kuda di sayap raja adalah formula skakmat yang sangat efektif.',
  },
  {
    id: 'p29',
    category: 'middlegame',
    difficulty: 'Sulit',
    fen: 'r1b1r1k1/ppp2ppp/8/4N3/2B2n2/8/PPP2PPP/R3R1K1 w - - 0 16',
    turn: 'w',
    solutionUci: 'c4f7',
    theme: 'Garpu Gajah Menyerang Benteng dan Raja',
    description: 'Gajah putih di c4 memukul f7 untuk skak Raja sekaligus mengincar Benteng e8!',
    hintPiece: 'Gajah putih di c4.',
    hintExplanation: 'Pukul pion f7 dengan Gajah.',
    trickExplanation: 'Serangan ganda memenangkan kualitas benteng gratis pada langkah berikutnya.',
  },
  {
    id: 'p30',
    category: 'middlegame',
    difficulty: 'Sedang',
    fen: 'r4rk1/ppp2ppp/2n5/3q4/3P4/5N2/PP1Q1PPP/R3R1K1 w - - 0 14',
    turn: 'w',
    solutionUci: 'e1e5',
    theme: 'Pengalihan Benteng di Jalur Pusat (Deflection)',
    description: 'Gunakan Benteng untuk mengusir Menteri hitam dari petak sentral d5.',
    hintPiece: 'Benteng putih di petak e1.',
    hintExplanation: 'Langkahkan Benteng ke e5 untuk menekan Menteri hitam.',
    trickExplanation: 'Mengusir perwira utama lawan merebut kendali penuh atas petak-petak kunci di babak tengah.',
  },
  {
    id: 'p31',
    category: 'middlegame',
    difficulty: 'Mudah',
    fen: 'r1b2rk1/pp3ppp/2n1p3/3p4/q1PP4/P1Q1PN2/1P3PPP/R3KB1R w KQ - 0 12',
    turn: 'w',
    solutionUci: 'b2b3',
    theme: 'Perangkap Menteri di Tepi Papan (Trapping the Queen)',
    description: 'Menteri hitam di a4 kehabisan petak pelarian yang aman. Jebak menteri tersebut!',
    hintPiece: 'Pion putih di b2.',
    hintExplanation: 'Dorong pion b2 ke b3 untuk menyerang Menteri a4 yang terkepung.',
    trickExplanation: 'Menteri yang masuk terlalu jauh ke wilayah musuh rawan terperangkap oleh perwira ringan.',
  },
  {
    id: 'p32',
    category: 'middlegame',
    difficulty: 'Sedang',
    fen: '2r2rk1/1pqb1ppp/p2p1n2/4p3/3BPP2/1BN5/PPP1Q1PP/R4RK1 w - - 0 14',
    turn: 'w',
    solutionUci: 'f4e5',
    theme: 'Pembukaan Jalur Tembak Benteng f',
    description: 'Pukul pion e5 untuk membuka jalur f bagi Benteng f1 yang menatap Raja Hitam!',
    hintPiece: 'Pion putih di f4.',
    hintExplanation: 'Pukul pion e5 dengan pion f4.',
    trickExplanation: 'Membuka jalur semi-terbuka memaksimalkan efisiensi tempur benteng.',
  },
  {
    id: 'p33',
    category: 'middlegame',
    difficulty: 'Sulit',
    fen: 'r2q1rk1/1b1nbppp/pp2p3/2ppP3/3P4/2N1PN2/PPQ2PPP/1BR2RK1 w - - 0 14',
    turn: 'w',
    solutionUci: 'c2h7',
    theme: 'Skakmat Baterai Menteri c2 dan Gajah b1',
    description: 'Formasi baterai Menteri c2 dan Gajah b1 siap menerkam petak h7. Tuntaskan kemenangan!',
    hintPiece: 'Menteri putih di c2.',
    hintExplanation: 'Pukul pion h7 dengan Menteri untuk skakmat mutlak.',
    trickExplanation: 'Baterai diagonal b1-h7 adalah salah satu pola mat paling mematikan dalam pertahanan Prancis.',
  },
  {
    id: 'p34',
    category: 'middlegame',
    difficulty: 'Sedang',
    fen: 'r1b2rk1/pp1n1ppp/1qn1p3/3pP3/1b1P4/1N1B1N2/PP1B1PPP/R2QK2R w KQ - 3 11',
    turn: 'w',
    solutionUci: 'd3h7',
    theme: 'Pengorbanan Tematik Pembongkar Sayap Raja',
    description: 'Gajah di d3 siap dikorbankan di h7 untuk memancing Raja Hitam keluar dari bentengnya.',
    hintPiece: 'Gajah putih di d3.',
    hintExplanation: 'Pukul pion h7 dengan Gajah untuk skak.',
    trickExplanation: 'Menghancurkan selubung pion raja membuka akses bagi Kuda g5 dan Menteri d1/h5.',
  },
  {
    id: 'p35',
    category: 'middlegame',
    difficulty: 'Mudah',
    fen: 'r4rk1/ppp2ppp/2n5/3q4/3P2b1/5N2/PP1Q1PPP/R3R1K1 w - - 0 15',
    turn: 'w',
    solutionUci: 'f3e5',
    theme: 'Garpu Kuda Sentralisasi',
    description: 'Tempatkan Kuda di e5 untuk menyerang Gajah g4 dan Kuda c6 lawan secara serentak.',
    hintPiece: 'Kuda putih di petak f3.',
    hintExplanation: 'Lompatkan Kuda ke e5.',
    trickExplanation: 'Sentralisasi kuda di e5/d5 meningkatkan jangkauan taktis serangan ke berbagai arah.',
  },
  {
    id: 'p36',
    category: 'middlegame',
    difficulty: 'Sedang',
    fen: '2r2rk1/1p1b1ppp/p2p4/3N4/4PP2/1B6/PPP3PP/2K4R w - - 0 18',
    turn: 'w',
    solutionUci: 'd5e7',
    theme: 'Garpu Kuda Kerajaan (Royal Fork)',
    description: 'Lompatkan Kuda ke e7 untuk menggarpu Raja g8 dan Benteng c8!',
    hintPiece: 'Kuda putih di d5.',
    hintExplanation: 'Lompatkan Kuda ke e7 untuk skak dan memenangkan Benteng c8.',
    trickExplanation: 'Garpu kuda adalah taktik paling sering menghasilkan keuntungan perwira masif.',
  },
  {
    id: 'p37',
    category: 'middlegame',
    difficulty: 'Sulit',
    fen: '2r1r1k1/pp3ppp/8/3q4/3n4/P2Q4/1P3PPP/1K1R3R b - - 1 20',
    turn: 'b',
    solutionUci: 'd5g2',
    theme: 'Pembersihan Pion Sayap dan Penyerangan Benteng',
    description: 'Menteri hitam memukul pion g2 untuk mengancam Benteng h1.',
    hintPiece: 'Menteri hitam di d5.',
    hintExplanation: 'Pukul pion g2 dengan Menteri hitam.',
    trickExplanation: 'Menyerang perwira berat musuh sambil merebut pion memecah konsentrasi pertahanan lawan.',
  },
  {
    id: 'p38',
    category: 'middlegame',
    difficulty: 'Sedang',
    fen: 'r2q1rk1/1pp1bppp/p1np1n2/4p1B1/2B1P1b1/2NP1N2/PPP1QPPP/R4RK1 w - - 2 9',
    turn: 'w',
    solutionUci: 'g5f6',
    theme: 'Eliminasi Perwira Pengawal Kunci',
    description: 'Pukul Kuda f6 untuk menghilangkan pengawal petak sentral d5.',
    hintPiece: 'Gajah putih di g5.',
    hintExplanation: 'Pukul Kuda f6 dengan Gajah g5.',
    trickExplanation: 'Menghilangkan pengawal (removing the defender) membuka pintu infiltrasi perwira kita ke petak lawan.',
  },

  // 39-50: ENDGAME MASTERY (Babak Akhir, Promosi & Skakmat)
  {
    id: 'p39',
    category: 'endgame',
    difficulty: 'Mudah',
    fen: '8/4P3/8/8/8/8/5k2/7K w - - 0 1',
    turn: 'w',
    solutionUci: 'e7e8q',
    theme: 'Promosi Menjadi Menteri Baru',
    description: 'Dorong pion e7 ke e8 untuk promosi menjadi Menteri baru dan memenangkan babak akhir.',
    hintPiece: 'Pion putih di petak e7.',
    hintExplanation: 'Dorong pion ke e8 dan pilih promosi Menteri (Q).',
    trickExplanation: 'Mempromosikan pion menjadi menteri adalah tujuan puncak dari strategi babak akhir.',
  },
  {
    id: 'p40',
    category: 'endgame',
    difficulty: 'Mudah',
    fen: '4k3/R7/4K3/8/8/8/8/8 w - - 0 1',
    turn: 'w',
    solutionUci: 'a7a8',
    theme: 'Skakmat Benteng Baris Dasar',
    description: 'Raja Putih di e6 mengunci petak pelarian raja lawan. Luncurkan Benteng ke a8 untuk skakmat!',
    hintPiece: 'Benteng putih di petak a7.',
    hintExplanation: 'Langkahkan Benteng ke a8 untuk skakmat langsung.',
    trickExplanation: 'Raja yang berada dalam posisi oposisi membantu benteng menuntaskan skakmat di baris tepi.',
  },
  {
    id: 'p41',
    category: 'endgame',
    difficulty: 'Sedang',
    fen: '8/8/8/8/8/5k2/R7/4K2R w - - 0 1',
    turn: 'w',
    solutionUci: 'h1h3',
    theme: 'Skak Tangga Dua Benteng (Lawnmower Mate)',
    description: 'Gunakan Benteng h1 untuk skak dan memotong baris ruang gerak raja Hitam.',
    hintPiece: 'Benteng putih di h1.',
    hintExplanation: 'Langkahkan Benteng ke h3 untuk skak memotong baris ketiga.',
    trickExplanation: 'Taktik mesin pemotong rumput (lawnmower) menggunakan dua benteng bergantian membatasi gerak raja.',
  },
  {
    id: 'p42',
    category: 'endgame',
    difficulty: 'Sedang',
    fen: '8/8/4k3/3p4/3K4/8/8/8 w - - 0 1',
    turn: 'w',
    solutionUci: 'd4d3',
    theme: 'Oposisi Vertikal Raja Babak Akhir',
    description: 'Tarik Raja ke d3 untuk mempertahankan keunggulan posisi dan mengunci raja lawan.',
    hintPiece: 'Raja putih di petak d4.',
    hintExplanation: 'Langkahkan Raja mundur ke d3.',
    trickExplanation: 'Oposisi raja adalah konsep fundamental untuk mengawal pion kita promosi atau menghadang pion lawan.',
  },
  {
    id: 'p43',
    category: 'endgame',
    difficulty: 'Sulit',
    fen: '8/8/8/3k4/1R6/2K5/8/8 w - - 0 1',
    turn: 'w',
    solutionUci: 'b4b5',
    theme: 'Pemotongan Wilayah Raja (Cutting Off the King)',
    description: 'Batasi ruang jelajah Raja Hitam ke sayap kiri papan dengan Benteng b4!',
    hintPiece: 'Benteng putih di petak b4.',
    hintExplanation: 'Langkahkan Benteng ke b5 untuk skak dan membatasi gerak Raja musuh.',
    trickExplanation: 'Memotong wilayah gerak raja lawan mempercepat proses penguncian ke sudut papan.',
  },
  {
    id: 'p44',
    category: 'endgame',
    difficulty: 'Mudah',
    fen: '6k1/5ppp/8/8/8/8/8/1R4K1 w - - 0 1',
    turn: 'w',
    solutionUci: 'b1b8',
    theme: 'Skakmat Baris Belakang Klasik (Back-Rank Mate)',
    description: 'Raja Hitam terperangkap di balik barisan pionnya sendiri di g7/h7. Berikan skakmat di b8!',
    hintPiece: 'Benteng putih di b1.',
    hintExplanation: 'Langkahkan Benteng ke b8 untuk skakmat baris dasar.',
    trickExplanation: 'Kurangnya lubang angin (luft) bagi raja adalah penyebab utama kekalahan mendadak di babak akhir.',
  },
  {
    id: 'p45',
    category: 'endgame',
    difficulty: 'Sedang',
    fen: '8/8/8/4k3/8/4K3/4P3/8 w - - 0 1',
    turn: 'w',
    solutionUci: 'e3d3',
    theme: 'Outflanking Raja Menuju Petak Kunci',
    description: 'Bermanuverlah ke d3 untuk membuka jalur maju bagi pion e2 menuju petak promosi.',
    hintPiece: 'Raja putih di petak e3.',
    hintExplanation: 'Langkahkan Raja ke petak d3.',
    trickExplanation: 'Outflanking memungkinkan raja kita melompati pertahanan lawan untuk mengawal pion.',
  },
  {
    id: 'p46',
    category: 'endgame',
    difficulty: 'Sulit',
    fen: '8/8/8/8/2k5/8/1pK5/8 b - - 0 1',
    turn: 'b',
    solutionUci: 'b2b1q',
    theme: 'Pengorbanan Umpan Promosi Pion (Decoy Promotion)',
    description: 'Promosikan pion b2 menjadi Menteri di b1 untuk memancing Raja putih meninggalkan petak c2!',
    hintPiece: 'Pion hitam di petak b2.',
    hintExplanation: 'Promosikan pion ke b1 menjadi Menteri.',
    trickExplanation: 'Promosi memaksa raja lawan memukul menteri dan membuka jalan bagi raja hitam menguasai petak kunci c3.',
  },
  {
    id: 'p47',
    category: 'endgame',
    difficulty: 'Mudah',
    fen: '8/8/8/8/4k3/8/5P2/4K3 w - - 0 1',
    turn: 'w',
    solutionUci: 'e1e2',
    theme: 'Mengambil Oposisi Depan Pion',
    description: 'Tempatkan Raja di e2 tepat di depan pion f2 untuk mengamankan jalur maju.',
    hintPiece: 'Raja putih di e1.',
    hintExplanation: 'Langkahkan Raja ke e2.',
    trickExplanation: 'Raja di depan pion adalah konfigurasi paling kuat untuk menjamin keberhasilan promosi.',
  },
  {
    id: 'p48',
    category: 'endgame',
    difficulty: 'Sedang',
    fen: '8/8/8/8/8/k7/1p6/1K6 b - - 0 1',
    turn: 'b',
    solutionUci: 'a3b3',
    theme: 'Kunci Oposisi Stalemate Trap Avoidance',
    description: 'Langkahkan Raja ke b3 untuk mengunci Raja Putih di petak b1.',
    hintPiece: 'Raja hitam di a3.',
    hintExplanation: 'Langkahkan Raja ke b3.',
    trickExplanation: 'Mengunci raja lawan di sudut papan memastikan kemenangan jika dilakukan tanpa menimbulkan stalemate.',
  },
  {
    id: 'p49',
    category: 'endgame',
    difficulty: 'Mudah',
    fen: '7k/5K2/6P1/8/8/8/8/8 w - - 0 1',
    turn: 'w',
    solutionUci: 'g6g7',
    theme: 'Dorongan Pion Menuju Skakmat',
    description: 'Dorong pion ke g7 untuk skak dan memaksa Raja Hitam masuk ke petak sudut h7.',
    hintPiece: 'Pion putih di petak g6.',
    hintExplanation: 'Dorong pion ke petak g7 dengan skak.',
    trickExplanation: 'Skak dengan pion di baris ke-7 membuka jalan promosi menteri yang mematikan pada langkah berikutnya.',
  },
  {
    id: 'p50',
    category: 'endgame',
    difficulty: 'Sulit',
    fen: '8/8/8/8/8/2k5/R7/2K5 w - - 0 1',
    turn: 'w',
    solutionUci: 'a2a3',
    theme: 'Skak Pembatas Baris Tepi Benteng',
    description: 'Gunakan Benteng di a2 untuk skak ke a3 dan memotong lajur pergerakan Raja Hitam!',
    hintPiece: 'Benteng putih di a2.',
    hintExplanation: 'Langkahkan Benteng ke a3 untuk skak.',
    trickExplanation: 'Skak samping benteng memaksa raja lawan mundur menjauh dari petak sentral.',
  },
];

console.log(`Validating and building ${rawPuzzles.length} puzzles...`);

const validatedPuzzles = rawPuzzles.map((p, idx) => {
  const c = new Chess();
  c.load(p.fen);
  if (c.turn() !== p.turn) {
    throw new Error(`Turn mismatch in ${p.id}: expected ${p.turn}, got ${c.turn()}`);
  }
  const from = p.solutionUci.slice(0, 2);
  const to = p.solutionUci.slice(2, 4);
  const promotion = p.solutionUci.length > 4 ? p.solutionUci[4] : undefined;
  const res = c.move({ from, to, promotion });
  if (!res) {
    throw new Error(`Illegal move in ${p.id}: ${p.solutionUci} on ${p.fen}`);
  }

  const isQuest = idx < 12 || (idx >= 24 && idx < 36);
  const xp = p.difficulty === 'Mudah' ? 50 : p.difficulty === 'Sedang' ? 100 : 175;
  const motif = res.san.includes('#') ? 'mate' : promotion ? 'promotion' : res.captured ? 'capture' : 'capture-check';

  return {
    id: p.id,
    category: p.category,
    difficulty: p.difficulty,
    track: isQuest ? 'quest' : 'puzzle',
    fen: p.fen,
    turn: p.turn,
    solutionUci: p.solutionUci,
    solutionSan: res.san,
    motif,
    theme: p.theme,
    description: p.description,
    hintPiece: p.hintPiece,
    hintExplanation: p.hintExplanation,
    trickExplanation: p.trickExplanation,
    xp,
  };
});

const fileHeader = `// AUTO-GENERATED oleh scripts/make_all_puzzles.js. JANGAN diedit manual.
// 50 Teka-Teki Catur Terverifikasi (chess.js) dengan Motif Taktis John A. Bain
// dan Terminologi Catur Standar Bahasa Indonesia (Menteri, Benteng, Gajah, Kuda, Pion, Raja).

export type PuzzleCategory = "opening" | "defense" | "middlegame" | "endgame" | "opponent";
export type PuzzleDifficulty = "Mudah" | "Sedang" | "Sulit";
export type PuzzleMotif = "mate" | "promotion" | "capture" | "capture-check";
export type PuzzleTrack = "quest" | "puzzle";

export type Puzzle = {
  id: string;
  category: PuzzleCategory;
  difficulty: PuzzleDifficulty;
  track: PuzzleTrack;
  fen: string;
  turn: "w" | "b";
  solutionUci: string;
  solutionSan: string;
  motif: PuzzleMotif;
  theme: string;
  description: string;
  hintPiece: string;
  hintExplanation: string;
  trickExplanation: string;
  xp: number;
};

export const PUZZLE_CATEGORIES: { id: PuzzleCategory | "all"; label: string }[] = [
  { id: "all", label: "Semua Kategori" },
  { id: "opening", label: "Pembukaan (Opening)" },
  { id: "defense", label: "Pertahanan (Defense)" },
  { id: "middlegame", label: "Babak Tengah (Middlegame)" },
  { id: "endgame", label: "Babak Akhir (Endgame)" },
  { id: "opponent", label: "Trik Lawan Live" },
];

export function byCategory(puzzles: Puzzle[], category: PuzzleCategory | "all"): Puzzle[] {
  if (category === "all") return puzzles;
  return puzzles.filter((p) => p.category === category);
}

export const QUEST_CHAPTERS: Puzzle[] = ${JSON.stringify(validatedPuzzles.filter(p => p.track === 'quest'), null, 2)};

export const PUZZLES: Puzzle[] = ${JSON.stringify(validatedPuzzles, null, 2)};
`;

fs.writeFileSync(path.join(__dirname, '../lib/puzzle-data.ts'), fileHeader);
console.log('Successfully generated lib/puzzle-data.ts with 50 verified puzzles!');
