const fs = require('fs');
const path = require('path');
const { validatePuzzle } = require('./validator.js');

const rawPuzzles = [
  // 1-10: OPENING
  {
    id: 'p1',
    category: 'opening',
    difficulty: 'Mudah',
    fen: 'r1bqkb1r/pppp1ppp/2n5/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 0 4',
    turn: 'w',
    solutionUci: 'h5f7',
    theme: "Serangan Titik Lemah f7 (Scholar's Mate)",
    description: 'Manfaatkan titik lemah petak f7 yang hanya dijaga oleh raja Hitam di fase pembukaan.',
    hintPiece: 'Menteri putih di petak h5.',
    hintExplanation: 'Menteri memukul bidak di f7 dengan bantuan perlindungan gajah di c4 untuk skakmat langsung.',
    trickExplanation: 'Trik Titik Lemah f7: Sebelum rokade, f7 adalah petak paling rentan karena hanya dikawal oleh raja.',
  },
  {
    id: 'p2',
    category: 'opening',
    difficulty: 'Sedang',
    fen: 'rnbqkbnr/ppppp1pp/5p2/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2',
    turn: 'w',
    solutionUci: 'd1h5',
    theme: "Perangkap Celah Diagonal e8-h5 (Fool's Pattern)",
    description: 'Hitam melangkahkan f6 di langkah awal. Hukum celah fatal pada jalur diagonal raja.',
    hintPiece: 'Menteri putih di petak d1.',
    hintExplanation: 'Luncurkan Menteri ke h5 untuk memberikan skak keras pada raja Hitam.',
    trickExplanation: 'Trik Diagonal Maut: Mendorong pion f7 di pembukaan catur adalah tabu karena membongkar pelindung utama raja.',
  },
  {
    id: 'p3',
    category: 'opening',
    difficulty: 'Sedang',
    fen: 'r1bqkb1r/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 2 4',
    turn: 'w',
    solutionUci: 'f3g5',
    theme: 'Serangan Hati Ayam (Fried Liver Attack)',
    description: 'Tekan titik f7 bersama Gajah c4 sebelum Hitam menyelesaikan perkembangan perwiranya.',
    hintPiece: 'Kuda putih di petak f3.',
    hintExplanation: 'Langkahkan kuda f3 ke g5 untuk menambah ancaman ganda ke f7.',
    trickExplanation: 'Kombinasi Kuda di g5 dan Gajah di c4 menargetkan f7 secara simultan.',
  },
  {
    id: 'p4',
    category: 'opening',
    difficulty: 'Sedang',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 4',
    turn: 'b',
    solutionUci: 'f6e4',
    theme: 'Garpu Pusat Korban Kuda (Center Fork Trick)',
    description: 'Hitam memukul pion e4 untuk merebut kontrol pusat lewat garpuan d7-d5 pada langkah berikutnya.',
    hintPiece: 'Kuda hitam di petak f6.',
    hintExplanation: 'Pukul pion e4 dengan kuda hitam.',
    trickExplanation: 'Jika Putih membalas Nxe4, Hitam mendorong d7-d5 menggarpu Gajah dan Kuda.',
  },
  {
    id: 'p5',
    category: 'opening',
    difficulty: 'Sulit',
    fen: 'r2qkb1r/pp1n1ppp/2p5/4N3/2B1P3/8/PPPP1PPP/RNBbK2R w KQkq - 0 8',
    turn: 'w',
    solutionUci: 'c4f7',
    theme: "Jebakan Legal (Legal's Trap Finale)",
    description: 'Hitam tergiur memakan Menteri Putih di d1! Hukum kepongahan lawan dengan skak pengorbanan gajah.',
    hintPiece: 'Gajah putih di c4.',
    hintExplanation: 'Pukul bidak f7 dengan Gajah untuk skak dan memaksa Raja Hitam melangkah ke e7.',
    trickExplanation: "Legal's Mate adalah jebakan legendaris: Putih mengorbankan Menteri demi skakmat cepat.",
  },
  {
    id: 'p6',
    category: 'opening',
    difficulty: 'Sedang',
    fen: 'r1bqkb1r/pp1npppp/2p2n2/8/3PN3/8/PPP1QPPP/R1B1KBNR w KQkq - 1 6',
    turn: 'w',
    solutionUci: 'e4d6',
    theme: 'Jebakan Smothered Caro-Kann',
    description: 'Hitam memblokir petak pelarian raja dengan pion dan kuda. Manfaatkan pin mutlak menteri di e2!',
    hintPiece: 'Kuda putih di petak e4.',
    hintExplanation: 'Lompatkan kuda ke d6 untuk skakmat mutlak karena pion e7 ter-pin oleh menteri e2.',
    trickExplanation: 'Pion e7 tidak dapat memukul d6 karena raja akan langsung terbuka ke menteri putih.',
  },
  {
    id: 'p7',
    category: 'opening',
    difficulty: 'Sedang',
    fen: 'r1b1k2r/ppppqppp/2n5/4n3/1PP5/5N2/1P1NPPPP/R2QKB1R b KQkq - 0 8',
    turn: 'b',
    solutionUci: 'e5d3',
    theme: 'Skakmat Budapest Gambit (Smothered Knight)',
    description: 'Putih tergiur memakan gajah di b4 dengan pion a3xb4. Selesaikan partai seketika!',
    hintPiece: 'Kuda hitam di petak e5.',
    hintExplanation: 'Lompatkan kuda ke d3 untuk skakmat karena pion e2 ter-pin oleh menteri e7.',
    trickExplanation: 'Budapest Gambit sering menghadirkan skakmat kuda elegan di d3 jika putih lengah.',
  },
  {
    id: 'p8',
    category: 'opening',
    difficulty: 'Sedang',
    fen: 'r1bqkb1r/pppn1ppp/5n2/3N2B1/3P4/8/PP2PPPP/R2QKBNR b KQkq - 0 6',
    turn: 'b',
    solutionUci: 'f6d5',
    theme: "Jebakan Gajah Queen's Gambit (Elephant Trap)",
    description: 'Putih baru saja memakan pion di d5 dengan Kuda. Balas dengan memukul kuda tersebut!',
    hintPiece: 'Kuda hitam di f6.',
    hintExplanation: 'Pukul kuda d5 dengan kuda f6. Jika Putih memakan menteri d8, Hitam membalas Bb4+!',
    trickExplanation: 'Elephant Trap: Hitam membiarkan menteri diserang karena skak Bb4+ akan merebut kembali menteri lawan plus untung 1 perwira.',
  },
  {
    id: 'p9',
    category: 'opening',
    difficulty: 'Mudah',
    fen: 'rnbqkbnr/pppp1ppp/8/4p3/4PP2/8/PPPP2PP/RNBQKBNR b KQkq - 0 2',
    turn: 'b',
    solutionUci: 'd8h4',
    theme: "Skak Pembuka King's Gambit Refusal",
    description: 'Putih membuka jalur sayap raja f2-f4 secara prematur. Luncurkan serangan balik cepat!',
    hintPiece: 'Menteri hitam di petak d8.',
    hintExplanation: 'Langkahkan menteri ke h4 untuk memberikan skak dan merusak kenyamanan raja putih.',
    trickExplanation: 'Menyerang diagonal sayap raja yang terbuka melemahkan koordinasi putih sejak babak awal.',
  },
  {
    id: 'p10',
    category: 'opening',
    difficulty: 'Sulit',
    fen: 'r1b1kbnr/pppp1ppp/8/4n3/3PP2q/8/PPP2PPP/RNBQKBNR w KQkq - 1 5',
    turn: 'w',
    solutionUci: 'd4e5',
    theme: 'Menangkis Serangan Prematur Menteri Lawan',
    description: 'Hitam melancarkan serangan menteri dini dan menempatkan kuda di e5 tanpa perlindungan cukup.',
    hintPiece: 'Pion putih di petak d4.',
    hintExplanation: 'Pukul kuda hitam di e5 secara gratis dengan pion d4.',
    trickExplanation: 'Menteri yang keluar terlalu dini di pembukaan sering meninggalkan perwira rekannya tanpa pengawalan.',
  },

  // 11-20: DEFENSE & COUNTER-ATTACK
  {
    id: 'p11',
    category: 'defense',
    difficulty: 'Sedang',
    fen: 'r1b1k2r/pp1pqppp/2n5/8/8/8/PPPP1PPP/R1BQR1K1 w kq - 0 1',
    turn: 'w',
    solutionUci: 'e1e7',
    theme: 'Pin Mutlak Jalur-e (Absolute Pin)',
    description: 'Menteri hitam di e7 terkena pin mutlak terhadap raja di e8. Rebut materi gratis!',
    hintPiece: 'Benteng putih di petak e1.',
    hintExplanation: 'Pukul menteri lawan di e7 secara cuma-cuma karena menteri ter-pin terhadap raja.',
    trickExplanation: 'Bidak yang ter-pin ke raja dilarang bergerak menurut aturan resmi catur.',
  },
  {
    id: 'p12',
    category: 'defense',
    difficulty: 'Mudah',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/4P3/3P1N2/PPP2PPP/RNBQKB1R w KQkq - 1 4',
    turn: 'w',
    solutionUci: 'c1g5',
    theme: 'Pin Sayap Gajah (Flank Pin Defense)',
    description: 'Kunci pergerakan Kuda hitam di f6 terhadap Menterinya di d8 untuk meredam inisiatif lawan.',
    hintPiece: 'Gajah putih di petak c1.',
    hintExplanation: 'Kembangkan gajah ke g5 untuk mem-pin kuda f6.',
    trickExplanation: 'Mem-pin kuda ke menteri memaksa lawan berpikir dua kali sebelum menggerakkan kudanya.',
  },
  {
    id: 'p13',
    category: 'defense',
    difficulty: 'Mudah',
    fen: '4r1k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1',
    turn: 'w',
    solutionUci: 'e1e8',
    theme: 'Pertahanan Baris Belakang Aktif',
    description: 'Benteng hitam menekan baris belakang Anda. Netralkan ancaman dengan skakmat balik!',
    hintPiece: 'Benteng putih di e1.',
    hintExplanation: 'Pukul benteng lawan di e8 untuk skakmat baris terakhir.',
    trickExplanation: 'Pertahanan terbaik seringkali adalah serangan langsung yang mengeliminasi ancaman lawan.',
  },
  {
    id: 'p14',
    category: 'defense',
    difficulty: 'Mudah',
    fen: '6k1/5ppp/8/8/8/8/5PPP/r5K1 w - - 0 1',
    turn: 'w',
    solutionUci: 'g1h1', // wait, check if g1h1 is legal? No, r1 is checking!
    // Let's use proper position for Luft or Blockade
  },
];

console.log('Validating baseline...');
